"""GCP Terraform variable definitions."""

from __future__ import annotations

from .common import (
    _COMMON_API_ENV,
    _COMMON_API_ENV_DISALLOW_SECRETS_VALIDATION,
    _COMMON_API_IMAGE,
    _COMMON_API_SECRETS,
    _COMMON_ENVIRONMENT,
    _COMMON_PROJECT_NAME,
    _COMMON_REGISTRY_PASSWORD,
    _COMMON_REGISTRY_SERVER,
    _COMMON_REGISTRY_USERNAME,
    _COMMON_WEB_ENV,
    _COMMON_WEB_IMAGE,
    _COMMON_WEB_SECRETS,
    _REQUIRED_PLACEHOLDER,
    _clone,
    _var,
)
from .models import (
    TerraformAllowedValuesCheck,
    TerraformComparisonCheck,
    TerraformCondition,
    TerraformRangeCheck,
    TerraformRequirementRule,
    TerraformValidationRule,
    TerraformVarCategory,
)

GCP_VARIABLES = (
    _COMMON_PROJECT_NAME,
    _COMMON_ENVIRONMENT,
    _var(
        "project_id",
        "string",
        "GCP project ID hosting the resources.",
        category=TerraformVarCategory.CORE,
        required=True,
        env_aliases=("GCP_PROJECT_ID",),
        template_value=_REQUIRED_PLACEHOLDER,
    ),
    _var(
        "gcp_sm_project_id",
        "string",
        "Optional Secret Manager project ID when secrets live outside project_id.",
        category=TerraformVarCategory.SECRETS,
        default="",
        env_aliases=("GCP_SM_PROJECT_ID",),
    ),
    _var(
        "region",
        "string",
        "GCP region for Cloud Run and managed services.",
        category=TerraformVarCategory.CORE,
        default="us-central1",
    ),
    _var(
        "enable_project_services",
        "bool",
        "Enable required GCP APIs (compute, vpcaccess, servicenetworking).",
        category=TerraformVarCategory.MISC,
        default=True,
        advanced=True,
    ),
    _var(
        "vpc_subnet_cidr",
        "string",
        "CIDR range for the primary VPC subnet.",
        category=TerraformVarCategory.NETWORK,
        default="10.30.0.0/16",
        advanced=True,
    ),
    _var(
        "vpc_connector_cidr",
        "string",
        "CIDR range for the Serverless VPC Access connector.",
        category=TerraformVarCategory.NETWORK,
        default="10.8.0.0/28",
        advanced=True,
    ),
    _var(
        "enable_private_service_access",
        "bool",
        "Enable Private Service Access for Cloud SQL and Memorystore.",
        category=TerraformVarCategory.NETWORK,
        default=True,
        advanced=True,
    ),
    _var(
        "private_service_cidr_prefix",
        "number",
        "CIDR prefix length for the Private Service Access range.",
        category=TerraformVarCategory.NETWORK,
        default=16,
        advanced=True,
    ),
    _COMMON_API_IMAGE,
    _COMMON_WEB_IMAGE,
    _var(
        "worker_image",
        "string",
        "Optional worker image (defaults to api_image when empty).",
        category=TerraformVarCategory.IMAGES,
        default="",
    ),
    _var(
        "enable_worker_service",
        "bool",
        "Deploy a dedicated worker service for billing retries.",
        category=TerraformVarCategory.SCALING,
        default=False,
    ),
    _var(
        "api_cpu",
        "number",
        "CPU cores for the API container.",
        category=TerraformVarCategory.COMPUTE,
        default=1,
    ),
    _var(
        "api_memory",
        "string",
        "Memory for the API container (Gi).",
        category=TerraformVarCategory.COMPUTE,
        default="2Gi",
    ),
    _var(
        "web_cpu",
        "number",
        "CPU cores for the web container.",
        category=TerraformVarCategory.COMPUTE,
        default=1,
    ),
    _var(
        "web_memory",
        "string",
        "Memory for the web container (Gi).",
        category=TerraformVarCategory.COMPUTE,
        default="2Gi",
    ),
    _var(
        "worker_cpu",
        "number",
        "CPU cores for the worker container.",
        category=TerraformVarCategory.COMPUTE,
        default=1,
    ),
    _var(
        "worker_memory",
        "string",
        "Memory for the worker container (Gi).",
        category=TerraformVarCategory.COMPUTE,
        default="2Gi",
    ),
    _var(
        "api_min_instances",
        "number",
        "Minimum number of API instances.",
        category=TerraformVarCategory.SCALING,
        default=0,
        advanced=True,
    ),
    _var(
        "api_max_instances",
        "number",
        "Maximum number of API instances.",
        category=TerraformVarCategory.SCALING,
        default=10,
        advanced=True,
    ),
    _var(
        "web_min_instances",
        "number",
        "Minimum number of web instances.",
        category=TerraformVarCategory.SCALING,
        default=0,
        advanced=True,
    ),
    _var(
        "web_max_instances",
        "number",
        "Maximum number of web instances.",
        category=TerraformVarCategory.SCALING,
        default=10,
        advanced=True,
    ),
    _var(
        "worker_min_instances",
        "number",
        "Minimum number of worker instances.",
        category=TerraformVarCategory.SCALING,
        default=0,
        advanced=True,
    ),
    _var(
        "worker_max_instances",
        "number",
        "Maximum number of worker instances.",
        category=TerraformVarCategory.SCALING,
        default=5,
        advanced=True,
    ),
    _var(
        "api_base_url",
        "string",
        "Public API base URL for the web app (e.g. https://api.example.com).",
        category=TerraformVarCategory.URLS,
        required=True,
        env_aliases=("API_BASE_URL",),
        template_value=_REQUIRED_PLACEHOLDER,
    ),
    _var(
        "app_public_url",
        "string",
        "Public web URL used by the API service (e.g. https://app.example.com).",
        category=TerraformVarCategory.URLS,
        required=True,
        env_aliases=("APP_PUBLIC_URL",),
        template_value=_REQUIRED_PLACEHOLDER,
    ),
    _var(
        "secrets_provider",
        "string",
        "Secrets provider used by the API service (SECRETS_PROVIDER).",
        category=TerraformVarCategory.SECRETS,
        default="gcp_sm",
        env_aliases=("SECRETS_PROVIDER",),
    ),
    _var(
        "auth_key_storage_provider",
        "string",
        (
            "Secrets provider used for key storage (AUTH_KEY_STORAGE_PROVIDER). "
            "Defaults to secrets_provider."
        ),
        category=TerraformVarCategory.SECRETS,
        default="",
        env_aliases=("AUTH_KEY_STORAGE_PROVIDER",),
    ),
    _var(
        "auth_key_secret_name",
        "string",
        "Secret Manager name for the Ed25519 keyset JSON (AUTH_KEY_SECRET_NAME).",
        category=TerraformVarCategory.SECRETS,
        default="",
        env_aliases=("AUTH_KEY_SECRET_NAME",),
    ),
    _var(
        "gcp_sm_signing_secret_name",
        "string",
        "Secret Manager secret name containing the signing secret.",
        category=TerraformVarCategory.SECRETS,
        default="",
        env_aliases=("GCP_SM_SIGNING_SECRET_NAME",),
    ),
    _var(
        "storage_provider",
        "string",
        "Storage provider for the API service (STORAGE_PROVIDER).",
        category=TerraformVarCategory.STORAGE,
        default="gcs",
        env_aliases=("STORAGE_PROVIDER",),
    ),
    _var(
        "storage_bucket_name",
        "string",
        "GCS bucket name for object storage.",
        category=TerraformVarCategory.STORAGE,
        default="assets",
        env_aliases=("GCS_BUCKET",),
    ),
    _var(
        "storage_location",
        "string",
        "GCS bucket location (defaults to region).",
        category=TerraformVarCategory.STORAGE,
        default="",
        advanced=True,
    ),
    _var(
        "storage_uniform_access",
        "bool",
        "Enable uniform bucket-level access.",
        category=TerraformVarCategory.STORAGE,
        default=True,
        advanced=True,
    ),
    _var(
        "storage_versioning_enabled",
        "bool",
        "Enable object versioning.",
        category=TerraformVarCategory.STORAGE,
        default=True,
        advanced=True,
    ),
    _var(
        "storage_force_destroy",
        "bool",
        "Allow bucket deletion with objects (dev only).",
        category=TerraformVarCategory.STORAGE,
        default=False,
        advanced=True,
    ),
    _clone(_COMMON_API_ENV, description="Additional non-sensitive env vars for the API service."),
    _clone(_COMMON_WEB_ENV, description="Additional non-sensitive env vars for the web service."),
    _clone(
        _COMMON_API_SECRETS,
        description="Secret references for the API service (Secret Manager resource IDs).",
    ),
    _clone(
        _COMMON_WEB_SECRETS,
        description="Secret references for the web service (Secret Manager resource IDs).",
    ),
    _COMMON_REGISTRY_SERVER,
    _COMMON_REGISTRY_USERNAME,
    _COMMON_REGISTRY_PASSWORD,
    _var(
        "db_name",
        "string",
        "Postgres database name.",
        category=TerraformVarCategory.DATABASE,
        default="agent_app",
    ),
    _var(
        "db_username",
        "string",
        "Postgres admin username.",
        category=TerraformVarCategory.DATABASE,
        default="agent_admin",
    ),
    _var(
        "db_password",
        "string",
        "Postgres admin password.",
        category=TerraformVarCategory.DATABASE,
        required=True,
        sensitive=True,
        template_value=_REQUIRED_PLACEHOLDER,
    ),
    _var(
        "db_tier",
        "string",
        "Cloud SQL machine tier.",
        category=TerraformVarCategory.DATABASE,
        default="db-custom-1-3840",
        advanced=True,
    ),
    _var(
        "db_disk_type",
        "string",
        "Cloud SQL disk type.",
        category=TerraformVarCategory.DATABASE,
        default="PD_SSD",
        advanced=True,
    ),
    _var(
        "db_disk_size_gb",
        "number",
        "Cloud SQL disk size (GB).",
        category=TerraformVarCategory.DATABASE,
        default=50,
        advanced=True,
    ),
    _var(
        "db_disk_autoresize",
        "bool",
        "Enable automatic disk resize.",
        category=TerraformVarCategory.DATABASE,
        default=True,
        advanced=True,
    ),
    _var(
        "db_availability_type",
        "string",
        "Availability type (ZONAL or REGIONAL).",
        category=TerraformVarCategory.DATABASE,
        default="ZONAL",
        advanced=True,
    ),
    _var(
        "db_backup_enabled",
        "bool",
        "Enable Cloud SQL automated backups.",
        category=TerraformVarCategory.DATABASE,
        default=True,
        advanced=True,
    ),
    _var(
        "db_backup_start_time",
        "string",
        "Backup start time (HH:MM, UTC).",
        category=TerraformVarCategory.DATABASE,
        default="03:00",
        advanced=True,
    ),
    _var(
        "db_backup_retention_count",
        "number",
        "Number of backups to retain.",
        category=TerraformVarCategory.DATABASE,
        default=7,
        advanced=True,
    ),
    _var(
        "db_point_in_time_recovery_enabled",
        "bool",
        "Enable point-in-time recovery.",
        category=TerraformVarCategory.DATABASE,
        default=True,
        advanced=True,
    ),
    _var(
        "db_deletion_protection",
        "bool",
        "Prevent accidental deletion of the Cloud SQL instance.",
        category=TerraformVarCategory.DATABASE,
        default=True,
        advanced=True,
    ),
    _var(
        "db_public_ipv4_enabled",
        "bool",
        "Expose Cloud SQL via public IPv4 (not recommended).",
        category=TerraformVarCategory.DATABASE,
        default=False,
        advanced=True,
    ),
    _var(
        "redis_tier",
        "string",
        "Memorystore tier (BASIC or STANDARD_HA).",
        category=TerraformVarCategory.REDIS,
        default="BASIC",
        advanced=True,
    ),
    _var(
        "redis_memory_size_gb",
        "number",
        "Memorystore memory size in GB.",
        category=TerraformVarCategory.REDIS,
        default=1,
        advanced=True,
    ),
    _var(
        "redis_version",
        "string",
        "Memorystore Redis version.",
        category=TerraformVarCategory.REDIS,
        default="REDIS_7_0",
        advanced=True,
    ),
    _var(
        "redis_auth_enabled",
        "bool",
        "Enable Redis AUTH.",
        category=TerraformVarCategory.REDIS,
        default=True,
        advanced=True,
    ),
    _var(
        "redis_transit_encryption_mode",
        "string",
        "Transit encryption mode for Redis (SERVER_AUTHENTICATION or DISABLED).",
        category=TerraformVarCategory.REDIS,
        default="SERVER_AUTHENTICATION",
        advanced=True,
    ),
)

GCP_REQUIREMENTS = (
    TerraformRequirementRule(
        when=(TerraformCondition(key="secrets_provider", any_of=("gcp_sm",)),),
        any_of=(
            "gcp_sm_signing_secret_name",
            "api_env.GCP_SM_SIGNING_SECRET_NAME",
            "api_secrets.GCP_SM_SIGNING_SECRET_NAME",
        ),
        message=(
            "gcp_sm_signing_secret_name is required when secrets_provider=gcp_sm "
            "(or provide GCP_SM_SIGNING_SECRET_NAME via api_env/api_secrets)."
        ),
    ),
    TerraformRequirementRule(
        when=(
            TerraformCondition(
                key="auth_key_storage_provider",
                any_of=("gcp_sm",),
                fallback_key="secrets_provider",
            ),
        ),
        any_of=(
            "auth_key_secret_name",
            "api_env.AUTH_KEY_SECRET_NAME",
            "api_secrets.AUTH_KEY_SECRET_NAME",
        ),
        message=(
            "auth_key_secret_name is required when auth_key_storage_provider=gcp_sm "
            "(or provide AUTH_KEY_SECRET_NAME via api_env/api_secrets)."
        ),
    ),
)

GCP_VALIDATIONS = (
    _COMMON_API_ENV_DISALLOW_SECRETS_VALIDATION,
    TerraformValidationRule(
        when=(),
        check=TerraformRangeCheck(
            key="private_service_cidr_prefix",
            min_value=16,
            max_value=24,
        ),
        message="private_service_cidr_prefix must be between 16 and 24.",
    ),
    TerraformValidationRule(
        when=(),
        check=TerraformComparisonCheck(
            left="api_max_instances",
            operator=">=",
            right="api_min_instances",
        ),
        message="api_max_instances must be >= api_min_instances.",
    ),
    TerraformValidationRule(
        when=(),
        check=TerraformComparisonCheck(
            left="web_max_instances",
            operator=">=",
            right="web_min_instances",
        ),
        message="web_max_instances must be >= web_min_instances.",
    ),
    TerraformValidationRule(
        when=(),
        check=TerraformComparisonCheck(
            left="worker_max_instances",
            operator=">=",
            right="worker_min_instances",
        ),
        message="worker_max_instances must be >= worker_min_instances.",
    ),
    TerraformValidationRule(
        when=(),
        check=TerraformAllowedValuesCheck(
            key="storage_provider",
            allowed=("gcs",),
        ),
        message='storage_provider must be "gcs" for the GCP blueprint.',
    ),
    TerraformValidationRule(
        when=(),
        check=TerraformAllowedValuesCheck(
            key="db_availability_type",
            allowed=("ZONAL", "REGIONAL"),
            case_insensitive=True,
        ),
        message="db_availability_type must be ZONAL or REGIONAL.",
    ),
    TerraformValidationRule(
        when=(TerraformCondition(key="enable_private_service_access", truthy=False),),
        check=TerraformAllowedValuesCheck(
            key="db_public_ipv4_enabled",
            allowed=(True,),
        ),
        message="db_public_ipv4_enabled must be true when enable_private_service_access=false.",
    ),
    TerraformValidationRule(
        when=(),
        check=TerraformAllowedValuesCheck(
            key="redis_tier",
            allowed=("BASIC", "STANDARD_HA"),
            case_insensitive=True,
        ),
        message="redis_tier must be BASIC or STANDARD_HA.",
    ),
    TerraformValidationRule(
        when=(),
        check=TerraformRangeCheck(
            key="redis_memory_size_gb",
            min_value=1,
        ),
        message="redis_memory_size_gb must be at least 1.",
    ),
    TerraformValidationRule(
        when=(),
        check=TerraformAllowedValuesCheck(
            key="redis_transit_encryption_mode",
            allowed=("SERVER_AUTHENTICATION", "DISABLED"),
            case_insensitive=True,
        ),
        message="redis_transit_encryption_mode must be SERVER_AUTHENTICATION or DISABLED.",
    ),
)

__all__ = ["GCP_REQUIREMENTS", "GCP_VALIDATIONS", "GCP_VARIABLES"]
