// This file is auto-generated by @hey-api/openapi-ts

import { client } from "./client.gen.ts";
import type {
  Client,
  Options as Options2,
  TDataShape,
} from "./client/index.ts";
import type {
  AdminResetPasswordApiV1AuthPasswordResetPostData,
  AdminResetPasswordApiV1AuthPasswordResetPostErrors,
  AdminResetPasswordApiV1AuthPasswordResetPostResponses,
  ApplyTestFixturesApiV1TestFixturesApplyPostData,
  ApplyTestFixturesApiV1TestFixturesApplyPostErrors,
  ApplyTestFixturesApiV1TestFixturesApplyPostResponses,
  ApproveSignupRequestApiV1AuthSignupRequestsRequestIdApprovePostData,
  ApproveSignupRequestApiV1AuthSignupRequestsRequestIdApprovePostErrors,
  ApproveSignupRequestApiV1AuthSignupRequestsRequestIdApprovePostResponses,
  AttachFileApiV1VectorStoresVectorStoreIdFilesPostData,
  AttachFileApiV1VectorStoresVectorStoreIdFilesPostErrors,
  AttachFileApiV1VectorStoresVectorStoreIdFilesPostResponses,
  BillingEventStreamApiV1BillingStreamGetData,
  BillingEventStreamApiV1BillingStreamGetErrors,
  BillingEventStreamApiV1BillingStreamGetResponses,
  BindAgentContainerApiV1ContainersAgentsAgentKeyContainerPostData,
  BindAgentContainerApiV1ContainersAgentsAgentKeyContainerPostErrors,
  BindAgentContainerApiV1ContainersAgentsAgentKeyContainerPostResponses,
  CancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPostData,
  CancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPostErrors,
  CancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPostResponses,
  CancelWorkflowRunApiV1WorkflowsRunsRunIdCancelPostData,
  CancelWorkflowRunApiV1WorkflowsRunsRunIdCancelPostErrors,
  CancelWorkflowRunApiV1WorkflowsRunsRunIdCancelPostResponses,
  ChangePasswordApiV1AuthPasswordChangePostData,
  ChangePasswordApiV1AuthPasswordChangePostErrors,
  ChangePasswordApiV1AuthPasswordChangePostResponses,
  ChatWithAgentApiV1ChatPostData,
  ChatWithAgentApiV1ChatPostErrors,
  ChatWithAgentApiV1ChatPostResponses,
  ConfirmPasswordResetApiV1AuthPasswordConfirmPostData,
  ConfirmPasswordResetApiV1AuthPasswordConfirmPostErrors,
  ConfirmPasswordResetApiV1AuthPasswordConfirmPostResponses,
  ConfirmWebhookChallengeApiV1StatusSubscriptionsChallengePostData,
  ConfirmWebhookChallengeApiV1StatusSubscriptionsChallengePostErrors,
  ConfirmWebhookChallengeApiV1StatusSubscriptionsChallengePostResponses,
  CreateContainerApiV1ContainersPostData,
  CreateContainerApiV1ContainersPostErrors,
  CreateContainerApiV1ContainersPostResponses,
  CreatePresignedUploadApiV1StorageObjectsUploadUrlPostData,
  CreatePresignedUploadApiV1StorageObjectsUploadUrlPostErrors,
  CreatePresignedUploadApiV1StorageObjectsUploadUrlPostResponses,
  CreateStatusSubscriptionApiV1StatusSubscriptionsPostData,
  CreateStatusSubscriptionApiV1StatusSubscriptionsPostErrors,
  CreateStatusSubscriptionApiV1StatusSubscriptionsPostResponses,
  CreateVectorStoreApiV1VectorStoresPostData,
  CreateVectorStoreApiV1VectorStoresPostErrors,
  CreateVectorStoreApiV1VectorStoresPostResponses,
  DeleteContainerApiV1ContainersContainerIdDeleteData,
  DeleteContainerApiV1ContainersContainerIdDeleteErrors,
  DeleteContainerApiV1ContainersContainerIdDeleteResponses,
  DeleteConversationApiV1ConversationsConversationIdDeleteData,
  DeleteConversationApiV1ConversationsConversationIdDeleteErrors,
  DeleteConversationApiV1ConversationsConversationIdDeleteResponses,
  DeleteFileApiV1VectorStoresVectorStoreIdFilesFileIdDeleteData,
  DeleteFileApiV1VectorStoresVectorStoreIdFilesFileIdDeleteErrors,
  DeleteFileApiV1VectorStoresVectorStoreIdFilesFileIdDeleteResponses,
  DeleteObjectApiV1StorageObjectsObjectIdDeleteData,
  DeleteObjectApiV1StorageObjectsObjectIdDeleteErrors,
  DeleteObjectApiV1StorageObjectsObjectIdDeleteResponses,
  DeleteVectorStoreApiV1VectorStoresVectorStoreIdDeleteData,
  DeleteVectorStoreApiV1VectorStoresVectorStoreIdDeleteErrors,
  DeleteVectorStoreApiV1VectorStoresVectorStoreIdDeleteResponses,
  GetAgentStatusApiV1AgentsAgentNameStatusGetData,
  GetAgentStatusApiV1AgentsAgentNameStatusGetErrors,
  GetAgentStatusApiV1AgentsAgentNameStatusGetResponses,
  GetContainerByIdApiV1ContainersContainerIdGetData,
  GetContainerByIdApiV1ContainersContainerIdGetErrors,
  GetContainerByIdApiV1ContainersContainerIdGetResponses,
  GetConversationApiV1ConversationsConversationIdGetData,
  GetConversationApiV1ConversationsConversationIdGetErrors,
  GetConversationApiV1ConversationsConversationIdGetResponses,
  GetCurrentUserInfoApiV1AuthMeGetData,
  GetCurrentUserInfoApiV1AuthMeGetResponses,
  GetDownloadUrlApiV1StorageObjectsObjectIdDownloadUrlGetData,
  GetDownloadUrlApiV1StorageObjectsObjectIdDownloadUrlGetErrors,
  GetDownloadUrlApiV1StorageObjectsObjectIdDownloadUrlGetResponses,
  GetFileApiV1VectorStoresVectorStoreIdFilesFileIdGetData,
  GetFileApiV1VectorStoresVectorStoreIdFilesFileIdGetErrors,
  GetFileApiV1VectorStoresVectorStoreIdFilesFileIdGetResponses,
  GetPlatformStatusApiV1StatusGetData,
  GetPlatformStatusApiV1StatusGetResponses,
  GetPlatformStatusRssAliasApiV1StatusRssGetData,
  GetPlatformStatusRssAliasApiV1StatusRssGetResponses,
  GetPlatformStatusRssApiV1StatusRssGetData,
  GetPlatformStatusRssApiV1StatusRssGetResponses,
  GetSignupAccessPolicyApiV1AuthSignupPolicyGetData,
  GetSignupAccessPolicyApiV1AuthSignupPolicyGetResponses,
  GetTenantSettingsApiV1TenantsSettingsGetData,
  GetTenantSettingsApiV1TenantsSettingsGetErrors,
  GetTenantSettingsApiV1TenantsSettingsGetResponses,
  GetTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGetData,
  GetTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGetErrors,
  GetTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGetResponses,
  GetVectorStoreApiV1VectorStoresVectorStoreIdGetData,
  GetVectorStoreApiV1VectorStoresVectorStoreIdGetErrors,
  GetVectorStoreApiV1VectorStoresVectorStoreIdGetResponses,
  GetWorkflowDescriptorApiV1WorkflowsWorkflowKeyGetData,
  GetWorkflowDescriptorApiV1WorkflowsWorkflowKeyGetErrors,
  GetWorkflowDescriptorApiV1WorkflowsWorkflowKeyGetResponses,
  GetWorkflowRunApiV1WorkflowsRunsRunIdGetData,
  GetWorkflowRunApiV1WorkflowsRunsRunIdGetErrors,
  GetWorkflowRunApiV1WorkflowsRunsRunIdGetResponses,
  HandleStripeWebhookWebhooksStripePostData,
  HandleStripeWebhookWebhooksStripePostResponses,
  HealthCheckHealthGetData,
  HealthCheckHealthGetResponses,
  IssueEmailVerificationTokenApiV1TestFixturesEmailVerificationTokenPostData,
  IssueEmailVerificationTokenApiV1TestFixturesEmailVerificationTokenPostErrors,
  IssueEmailVerificationTokenApiV1TestFixturesEmailVerificationTokenPostResponses,
  IssueInviteApiV1AuthInvitesPostData,
  IssueInviteApiV1AuthInvitesPostErrors,
  IssueInviteApiV1AuthInvitesPostResponses,
  IssueServiceAccountTokenApiV1AuthServiceAccountsIssuePostData,
  IssueServiceAccountTokenApiV1AuthServiceAccountsIssuePostErrors,
  IssueServiceAccountTokenApiV1AuthServiceAccountsIssuePostResponses,
  IssueServiceAccountTokenFromBrowserApiV1AuthServiceAccountsBrowserIssuePostData,
  IssueServiceAccountTokenFromBrowserApiV1AuthServiceAccountsBrowserIssuePostErrors,
  IssueServiceAccountTokenFromBrowserApiV1AuthServiceAccountsBrowserIssuePostResponses,
  ListAvailableAgentsApiV1AgentsGetData,
  ListAvailableAgentsApiV1AgentsGetResponses,
  ListAvailableToolsApiV1ToolsGetData,
  ListAvailableToolsApiV1ToolsGetResponses,
  ListBillingEventsApiV1BillingTenantsTenantIdEventsGetData,
  ListBillingEventsApiV1BillingTenantsTenantIdEventsGetErrors,
  ListBillingEventsApiV1BillingTenantsTenantIdEventsGetResponses,
  ListBillingPlansApiV1BillingPlansGetData,
  ListBillingPlansApiV1BillingPlansGetResponses,
  ListContainersApiV1ContainersGetData,
  ListContainersApiV1ContainersGetErrors,
  ListContainersApiV1ContainersGetResponses,
  ListConversationsApiV1ConversationsGetData,
  ListConversationsApiV1ConversationsGetErrors,
  ListConversationsApiV1ConversationsGetResponses,
  ListFilesApiV1VectorStoresVectorStoreIdFilesGetData,
  ListFilesApiV1VectorStoresVectorStoreIdFilesGetErrors,
  ListFilesApiV1VectorStoresVectorStoreIdFilesGetResponses,
  ListInvitesApiV1AuthInvitesGetData,
  ListInvitesApiV1AuthInvitesGetErrors,
  ListInvitesApiV1AuthInvitesGetResponses,
  ListObjectsApiV1StorageObjectsGetData,
  ListObjectsApiV1StorageObjectsGetErrors,
  ListObjectsApiV1StorageObjectsGetResponses,
  ListServiceAccountTokensApiV1AuthServiceAccountsTokensGetData,
  ListServiceAccountTokensApiV1AuthServiceAccountsTokensGetErrors,
  ListServiceAccountTokensApiV1AuthServiceAccountsTokensGetResponses,
  ListSignupRequestsApiV1AuthSignupRequestsGetData,
  ListSignupRequestsApiV1AuthSignupRequestsGetErrors,
  ListSignupRequestsApiV1AuthSignupRequestsGetResponses,
  ListStatusSubscriptionsApiV1StatusSubscriptionsGetData,
  ListStatusSubscriptionsApiV1StatusSubscriptionsGetErrors,
  ListStatusSubscriptionsApiV1StatusSubscriptionsGetResponses,
  ListUserSessionsApiV1AuthSessionsGetData,
  ListUserSessionsApiV1AuthSessionsGetErrors,
  ListUserSessionsApiV1AuthSessionsGetResponses,
  ListVectorStoresApiV1VectorStoresGetData,
  ListVectorStoresApiV1VectorStoresGetErrors,
  ListVectorStoresApiV1VectorStoresGetResponses,
  ListWorkflowRunsApiV1WorkflowsRunsGetData,
  ListWorkflowRunsApiV1WorkflowsRunsGetErrors,
  ListWorkflowRunsApiV1WorkflowsRunsGetResponses,
  ListWorkflowsApiV1WorkflowsGetData,
  ListWorkflowsApiV1WorkflowsGetErrors,
  ListWorkflowsApiV1WorkflowsGetResponses,
  LoginForAccessTokenApiV1AuthTokenPostData,
  LoginForAccessTokenApiV1AuthTokenPostErrors,
  LoginForAccessTokenApiV1AuthTokenPostResponses,
  LogoutAllSessionsApiV1AuthLogoutAllPostData,
  LogoutAllSessionsApiV1AuthLogoutAllPostResponses,
  LogoutSessionApiV1AuthLogoutPostData,
  LogoutSessionApiV1AuthLogoutPostErrors,
  LogoutSessionApiV1AuthLogoutPostResponses,
  ReadinessCheckHealthReadyGetData,
  ReadinessCheckHealthReadyGetResponses,
  RecordUsageApiV1BillingTenantsTenantIdUsagePostData,
  RecordUsageApiV1BillingTenantsTenantIdUsagePostErrors,
  RecordUsageApiV1BillingTenantsTenantIdUsagePostResponses,
  RefreshAccessTokenApiV1AuthRefreshPostData,
  RefreshAccessTokenApiV1AuthRefreshPostErrors,
  RefreshAccessTokenApiV1AuthRefreshPostResponses,
  RegisterTenantApiV1AuthRegisterPostData,
  RegisterTenantApiV1AuthRegisterPostErrors,
  RegisterTenantApiV1AuthRegisterPostResponses,
  RejectSignupRequestApiV1AuthSignupRequestsRequestIdRejectPostData,
  RejectSignupRequestApiV1AuthSignupRequestsRequestIdRejectPostErrors,
  RejectSignupRequestApiV1AuthSignupRequestsRequestIdRejectPostResponses,
  RequestPasswordResetApiV1AuthPasswordForgotPostData,
  RequestPasswordResetApiV1AuthPasswordForgotPostErrors,
  RequestPasswordResetApiV1AuthPasswordForgotPostResponses,
  ResendStatusIncidentApiV1StatusIncidentsIncidentIdResendPostData,
  ResendStatusIncidentApiV1StatusIncidentsIncidentIdResendPostErrors,
  ResendStatusIncidentApiV1StatusIncidentsIncidentIdResendPostResponses,
  RevokeInviteApiV1AuthInvitesInviteIdRevokePostData,
  RevokeInviteApiV1AuthInvitesInviteIdRevokePostErrors,
  RevokeInviteApiV1AuthInvitesInviteIdRevokePostResponses,
  RevokeServiceAccountTokenApiV1AuthServiceAccountsTokensJtiRevokePostData,
  RevokeServiceAccountTokenApiV1AuthServiceAccountsTokensJtiRevokePostErrors,
  RevokeServiceAccountTokenApiV1AuthServiceAccountsTokensJtiRevokePostResponses,
  RevokeStatusSubscriptionApiV1StatusSubscriptionsSubscriptionIdDeleteData,
  RevokeStatusSubscriptionApiV1StatusSubscriptionsSubscriptionIdDeleteErrors,
  RevokeStatusSubscriptionApiV1StatusSubscriptionsSubscriptionIdDeleteResponses,
  RevokeUserSessionApiV1AuthSessionsSessionIdDeleteData,
  RevokeUserSessionApiV1AuthSessionsSessionIdDeleteErrors,
  RevokeUserSessionApiV1AuthSessionsSessionIdDeleteResponses,
  RunWorkflowApiV1WorkflowsWorkflowKeyRunPostData,
  RunWorkflowApiV1WorkflowsWorkflowKeyRunPostErrors,
  RunWorkflowApiV1WorkflowsWorkflowKeyRunPostResponses,
  RunWorkflowStreamApiV1WorkflowsWorkflowKeyRunStreamPostData,
  RunWorkflowStreamApiV1WorkflowsWorkflowKeyRunStreamPostErrors,
  RunWorkflowStreamApiV1WorkflowsWorkflowKeyRunStreamPostResponses,
  SearchConversationsApiV1ConversationsSearchGetData,
  SearchConversationsApiV1ConversationsSearchGetErrors,
  SearchConversationsApiV1ConversationsSearchGetResponses,
  SearchVectorStoreApiV1VectorStoresVectorStoreIdSearchPostData,
  SearchVectorStoreApiV1VectorStoresVectorStoreIdSearchPostErrors,
  SearchVectorStoreApiV1VectorStoresVectorStoreIdSearchPostResponses,
  SendEmailVerificationApiV1AuthEmailSendPostData,
  SendEmailVerificationApiV1AuthEmailSendPostResponses,
  StartSubscriptionApiV1BillingTenantsTenantIdSubscriptionPostData,
  StartSubscriptionApiV1BillingTenantsTenantIdSubscriptionPostErrors,
  StartSubscriptionApiV1BillingTenantsTenantIdSubscriptionPostResponses,
  StorageHealthHealthStorageGetData,
  StorageHealthHealthStorageGetResponses,
  StreamChatWithAgentApiV1ChatStreamPostData,
  StreamChatWithAgentApiV1ChatStreamPostErrors,
  StreamChatWithAgentApiV1ChatStreamPostResponses,
  SubmitAccessRequestApiV1AuthRequestAccessPostData,
  SubmitAccessRequestApiV1AuthRequestAccessPostErrors,
  SubmitAccessRequestApiV1AuthRequestAccessPostResponses,
  UnbindAgentContainerApiV1ContainersAgentsAgentKeyContainerDeleteData,
  UnbindAgentContainerApiV1ContainersAgentsAgentKeyContainerDeleteErrors,
  UnbindAgentContainerApiV1ContainersAgentsAgentKeyContainerDeleteResponses,
  UpdateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatchData,
  UpdateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatchErrors,
  UpdateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatchResponses,
  UpdateTenantSettingsApiV1TenantsSettingsPutData,
  UpdateTenantSettingsApiV1TenantsSettingsPutErrors,
  UpdateTenantSettingsApiV1TenantsSettingsPutResponses,
  VerifyEmailTokenApiV1AuthEmailVerifyPostData,
  VerifyEmailTokenApiV1AuthEmailVerifyPostErrors,
  VerifyEmailTokenApiV1AuthEmailVerifyPostResponses,
  VerifyStatusSubscriptionApiV1StatusSubscriptionsVerifyPostData,
  VerifyStatusSubscriptionApiV1StatusSubscriptionsVerifyPostErrors,
  VerifyStatusSubscriptionApiV1StatusSubscriptionsVerifyPostResponses,
} from "./types.gen.ts";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Health Check
 *
 * Basic liveness probe.
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckHealthGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    HealthCheckHealthGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/health",
    ...options,
  });
};

/**
 * Readiness Check
 *
 * Readiness probe for orchestrators (extend with dependency checks).
 */
export const readinessCheckHealthReadyGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ReadinessCheckHealthReadyGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadinessCheckHealthReadyGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/health/ready",
    ...options,
  });
};

/**
 * Storage Health
 *
 * Storage provider health (informational; does not gate readiness).
 */
export const storageHealthHealthStorageGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<StorageHealthHealthStorageGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    StorageHealthHealthStorageGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/health/storage",
    ...options,
  });
};

/**
 * Handle Stripe Webhook
 */
export const handleStripeWebhookWebhooksStripePost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<HandleStripeWebhookWebhooksStripePostData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    HandleStripeWebhookWebhooksStripePostResponses,
    unknown,
    ThrowOnError
  >({
    url: "/webhooks/stripe",
    ...options,
  });
};

/**
 * Login For Access Token
 *
 * Authenticate a user and mint fresh access/refresh tokens.
 */
export const loginForAccessTokenApiV1AuthTokenPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<LoginForAccessTokenApiV1AuthTokenPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    LoginForAccessTokenApiV1AuthTokenPostResponses,
    LoginForAccessTokenApiV1AuthTokenPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/auth/token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Refresh Access Token
 *
 * Exchange a refresh token for a new access/refresh pair.
 */
export const refreshAccessTokenApiV1AuthRefreshPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RefreshAccessTokenApiV1AuthRefreshPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    RefreshAccessTokenApiV1AuthRefreshPostResponses,
    RefreshAccessTokenApiV1AuthRefreshPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/auth/refresh",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Logout Session
 *
 * Revoke a single refresh token for the authenticated user.
 */
export const logoutSessionApiV1AuthLogoutPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<LogoutSessionApiV1AuthLogoutPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    LogoutSessionApiV1AuthLogoutPostResponses,
    LogoutSessionApiV1AuthLogoutPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/logout",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Logout All Sessions
 *
 * Revoke every refresh token tied to the authenticated user.
 */
export const logoutAllSessionsApiV1AuthLogoutAllPost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<LogoutAllSessionsApiV1AuthLogoutAllPostData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    LogoutAllSessionsApiV1AuthLogoutAllPostResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/logout/all",
    ...options,
  });
};

/**
 * List User Sessions
 *
 * Return paginated session/device metadata for the authenticated user.
 */
export const listUserSessionsApiV1AuthSessionsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListUserSessionsApiV1AuthSessionsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListUserSessionsApiV1AuthSessionsGetResponses,
    ListUserSessionsApiV1AuthSessionsGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/sessions",
    ...options,
  });
};

/**
 * Revoke User Session
 *
 * Revoke a specific session/device for the authenticated user.
 */
export const revokeUserSessionApiV1AuthSessionsSessionIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RevokeUserSessionApiV1AuthSessionsSessionIdDeleteData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).delete<
    RevokeUserSessionApiV1AuthSessionsSessionIdDeleteResponses,
    RevokeUserSessionApiV1AuthSessionsSessionIdDeleteErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/sessions/{session_id}",
    ...options,
  });
};

/**
 * Get Current User Info
 *
 * Return metadata about the current authenticated user.
 */
export const getCurrentUserInfoApiV1AuthMeGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetCurrentUserInfoApiV1AuthMeGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetCurrentUserInfoApiV1AuthMeGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/me",
    ...options,
  });
};

/**
 * Send Email Verification
 */
export const sendEmailVerificationApiV1AuthEmailSendPost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    SendEmailVerificationApiV1AuthEmailSendPostData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    SendEmailVerificationApiV1AuthEmailSendPostResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/email/send",
    ...options,
  });
};

/**
 * Verify Email Token
 */
export const verifyEmailTokenApiV1AuthEmailVerifyPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<VerifyEmailTokenApiV1AuthEmailVerifyPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    VerifyEmailTokenApiV1AuthEmailVerifyPostResponses,
    VerifyEmailTokenApiV1AuthEmailVerifyPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/auth/email/verify",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Request Password Reset
 */
export const requestPasswordResetApiV1AuthPasswordForgotPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RequestPasswordResetApiV1AuthPasswordForgotPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    RequestPasswordResetApiV1AuthPasswordForgotPostResponses,
    RequestPasswordResetApiV1AuthPasswordForgotPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/auth/password/forgot",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Confirm Password Reset
 */
export const confirmPasswordResetApiV1AuthPasswordConfirmPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ConfirmPasswordResetApiV1AuthPasswordConfirmPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    ConfirmPasswordResetApiV1AuthPasswordConfirmPostResponses,
    ConfirmPasswordResetApiV1AuthPasswordConfirmPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/auth/password/confirm",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Change Password
 */
export const changePasswordApiV1AuthPasswordChangePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ChangePasswordApiV1AuthPasswordChangePostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ChangePasswordApiV1AuthPasswordChangePostResponses,
    ChangePasswordApiV1AuthPasswordChangePostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/password/change",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Admin Reset Password
 */
export const adminResetPasswordApiV1AuthPasswordResetPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AdminResetPasswordApiV1AuthPasswordResetPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    AdminResetPasswordApiV1AuthPasswordResetPostResponses,
    AdminResetPasswordApiV1AuthPasswordResetPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/password/reset",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Issue Service Account Token
 *
 * Mint a refresh token for a registered service account.
 */
export const issueServiceAccountTokenApiV1AuthServiceAccountsIssuePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    IssueServiceAccountTokenApiV1AuthServiceAccountsIssuePostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    IssueServiceAccountTokenApiV1AuthServiceAccountsIssuePostResponses,
    IssueServiceAccountTokenApiV1AuthServiceAccountsIssuePostErrors,
    ThrowOnError
  >({
    url: "/api/v1/auth/service-accounts/issue",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Issue Service Account Token From Browser
 */
export const issueServiceAccountTokenFromBrowserApiV1AuthServiceAccountsBrowserIssuePost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      IssueServiceAccountTokenFromBrowserApiV1AuthServiceAccountsBrowserIssuePostData,
      ThrowOnError
    >,
  ) => {
    return (options.client ?? client).post<
      IssueServiceAccountTokenFromBrowserApiV1AuthServiceAccountsBrowserIssuePostResponses,
      IssueServiceAccountTokenFromBrowserApiV1AuthServiceAccountsBrowserIssuePostErrors,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/api/v1/auth/service-accounts/browser-issue",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  };

/**
 * List Service Account Tokens
 */
export const listServiceAccountTokensApiV1AuthServiceAccountsTokensGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ListServiceAccountTokensApiV1AuthServiceAccountsTokensGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    ListServiceAccountTokensApiV1AuthServiceAccountsTokensGetResponses,
    ListServiceAccountTokensApiV1AuthServiceAccountsTokensGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/service-accounts/tokens",
    ...options,
  });
};

/**
 * Revoke Service Account Token
 */
export const revokeServiceAccountTokenApiV1AuthServiceAccountsTokensJtiRevokePost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      RevokeServiceAccountTokenApiV1AuthServiceAccountsTokensJtiRevokePostData,
      ThrowOnError
    >,
  ) => {
    return (options.client ?? client).post<
      RevokeServiceAccountTokenApiV1AuthServiceAccountsTokensJtiRevokePostResponses,
      RevokeServiceAccountTokenApiV1AuthServiceAccountsTokensJtiRevokePostErrors,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/api/v1/auth/service-accounts/tokens/{jti}/revoke",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  };

/**
 * Get Signup Access Policy
 */
export const getSignupAccessPolicyApiV1AuthSignupPolicyGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    GetSignupAccessPolicyApiV1AuthSignupPolicyGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    GetSignupAccessPolicyApiV1AuthSignupPolicyGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/v1/auth/signup-policy",
    ...options,
  });
};

/**
 * Register Tenant
 */
export const registerTenantApiV1AuthRegisterPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RegisterTenantApiV1AuthRegisterPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    RegisterTenantApiV1AuthRegisterPostResponses,
    RegisterTenantApiV1AuthRegisterPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Submit Access Request
 */
export const submitAccessRequestApiV1AuthRequestAccessPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    SubmitAccessRequestApiV1AuthRequestAccessPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    SubmitAccessRequestApiV1AuthRequestAccessPostResponses,
    SubmitAccessRequestApiV1AuthRequestAccessPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/auth/request-access",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Signup Requests
 */
export const listSignupRequestsApiV1AuthSignupRequestsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ListSignupRequestsApiV1AuthSignupRequestsGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    ListSignupRequestsApiV1AuthSignupRequestsGetResponses,
    ListSignupRequestsApiV1AuthSignupRequestsGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/signup-requests",
    ...options,
  });
};

/**
 * Approve Signup Request
 */
export const approveSignupRequestApiV1AuthSignupRequestsRequestIdApprovePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ApproveSignupRequestApiV1AuthSignupRequestsRequestIdApprovePostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    ApproveSignupRequestApiV1AuthSignupRequestsRequestIdApprovePostResponses,
    ApproveSignupRequestApiV1AuthSignupRequestsRequestIdApprovePostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/signup-requests/{request_id}/approve",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Reject Signup Request
 */
export const rejectSignupRequestApiV1AuthSignupRequestsRequestIdRejectPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RejectSignupRequestApiV1AuthSignupRequestsRequestIdRejectPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    RejectSignupRequestApiV1AuthSignupRequestsRequestIdRejectPostResponses,
    RejectSignupRequestApiV1AuthSignupRequestsRequestIdRejectPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/signup-requests/{request_id}/reject",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Invites
 */
export const listInvitesApiV1AuthInvitesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListInvitesApiV1AuthInvitesGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListInvitesApiV1AuthInvitesGetResponses,
    ListInvitesApiV1AuthInvitesGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/invites",
    ...options,
  });
};

/**
 * Issue Invite
 */
export const issueInviteApiV1AuthInvitesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<IssueInviteApiV1AuthInvitesPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    IssueInviteApiV1AuthInvitesPostResponses,
    IssueInviteApiV1AuthInvitesPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/invites",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Revoke Invite
 */
export const revokeInviteApiV1AuthInvitesInviteIdRevokePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RevokeInviteApiV1AuthInvitesInviteIdRevokePostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    RevokeInviteApiV1AuthInvitesInviteIdRevokePostResponses,
    RevokeInviteApiV1AuthInvitesInviteIdRevokePostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/invites/{invite_id}/revoke",
    ...options,
  });
};

/**
 * Chat With Agent
 *
 * Send a message to the agent framework and receive a full response.
 */
export const chatWithAgentApiV1ChatPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ChatWithAgentApiV1ChatPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ChatWithAgentApiV1ChatPostResponses,
    ChatWithAgentApiV1ChatPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/chat",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Stream Chat With Agent
 *
 * Provide an SSE stream for real-time agent responses.
 */
export const streamChatWithAgentApiV1ChatStreamPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<StreamChatWithAgentApiV1ChatStreamPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    StreamChatWithAgentApiV1ChatStreamPostResponses,
    StreamChatWithAgentApiV1ChatStreamPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/chat/stream",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Available Agents
 *
 * Return all agents registered with the platform.
 */
export const listAvailableAgentsApiV1AgentsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListAvailableAgentsApiV1AgentsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListAvailableAgentsApiV1AgentsGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/agents",
    ...options,
  });
};

/**
 * Get Agent Status
 *
 * Return health/status details for a specific agent.
 */
export const getAgentStatusApiV1AgentsAgentNameStatusGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetAgentStatusApiV1AgentsAgentNameStatusGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).get<
    GetAgentStatusApiV1AgentsAgentNameStatusGetResponses,
    GetAgentStatusApiV1AgentsAgentNameStatusGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/agents/{agent_name}/status",
    ...options,
  });
};

/**
 * List Workflows
 */
export const listWorkflowsApiV1WorkflowsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListWorkflowsApiV1WorkflowsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListWorkflowsApiV1WorkflowsGetResponses,
    ListWorkflowsApiV1WorkflowsGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/workflows",
    ...options,
  });
};

/**
 * Run Workflow
 */
export const runWorkflowApiV1WorkflowsWorkflowKeyRunPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RunWorkflowApiV1WorkflowsWorkflowKeyRunPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    RunWorkflowApiV1WorkflowsWorkflowKeyRunPostResponses,
    RunWorkflowApiV1WorkflowsWorkflowKeyRunPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/workflows/{workflow_key}/run",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Workflow Runs
 */
export const listWorkflowRunsApiV1WorkflowsRunsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListWorkflowRunsApiV1WorkflowsRunsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListWorkflowRunsApiV1WorkflowsRunsGetResponses,
    ListWorkflowRunsApiV1WorkflowsRunsGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/workflows/runs",
    ...options,
  });
};

/**
 * Get Workflow Run
 */
export const getWorkflowRunApiV1WorkflowsRunsRunIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetWorkflowRunApiV1WorkflowsRunsRunIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetWorkflowRunApiV1WorkflowsRunsRunIdGetResponses,
    GetWorkflowRunApiV1WorkflowsRunsRunIdGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/workflows/runs/{run_id}",
    ...options,
  });
};

/**
 * Cancel Workflow Run
 */
export const cancelWorkflowRunApiV1WorkflowsRunsRunIdCancelPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CancelWorkflowRunApiV1WorkflowsRunsRunIdCancelPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    CancelWorkflowRunApiV1WorkflowsRunsRunIdCancelPostResponses,
    CancelWorkflowRunApiV1WorkflowsRunsRunIdCancelPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/workflows/runs/{run_id}/cancel",
    ...options,
  });
};

/**
 * Run Workflow Stream
 */
export const runWorkflowStreamApiV1WorkflowsWorkflowKeyRunStreamPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RunWorkflowStreamApiV1WorkflowsWorkflowKeyRunStreamPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    RunWorkflowStreamApiV1WorkflowsWorkflowKeyRunStreamPostResponses,
    RunWorkflowStreamApiV1WorkflowsWorkflowKeyRunStreamPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/workflows/{workflow_key}/run-stream",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Workflow Descriptor
 */
export const getWorkflowDescriptorApiV1WorkflowsWorkflowKeyGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetWorkflowDescriptorApiV1WorkflowsWorkflowKeyGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).get<
    GetWorkflowDescriptorApiV1WorkflowsWorkflowKeyGetResponses,
    GetWorkflowDescriptorApiV1WorkflowsWorkflowKeyGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/workflows/{workflow_key}",
    ...options,
  });
};

/**
 * List Conversations
 *
 * List stored conversations ordered by recency.
 */
export const listConversationsApiV1ConversationsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListConversationsApiV1ConversationsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListConversationsApiV1ConversationsGetResponses,
    ListConversationsApiV1ConversationsGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/conversations",
    ...options,
  });
};

/**
 * Search Conversations
 *
 * Search conversations by message text.
 */
export const searchConversationsApiV1ConversationsSearchGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    SearchConversationsApiV1ConversationsSearchGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).get<
    SearchConversationsApiV1ConversationsSearchGetResponses,
    SearchConversationsApiV1ConversationsSearchGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/conversations/search",
    ...options,
  });
};

/**
 * Delete Conversation
 *
 * Remove all stored messages for the given conversation.
 */
export const deleteConversationApiV1ConversationsConversationIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteConversationApiV1ConversationsConversationIdDeleteData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).delete<
    DeleteConversationApiV1ConversationsConversationIdDeleteResponses,
    DeleteConversationApiV1ConversationsConversationIdDeleteErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/conversations/{conversation_id}",
    ...options,
  });
};

/**
 * Get Conversation
 *
 * Return the full conversation history for a specific conversation.
 */
export const getConversationApiV1ConversationsConversationIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetConversationApiV1ConversationsConversationIdGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).get<
    GetConversationApiV1ConversationsConversationIdGetResponses,
    GetConversationApiV1ConversationsConversationIdGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/conversations/{conversation_id}",
    ...options,
  });
};

/**
 * List Available Tools
 *
 * Return metadata about registered tools.
 */
export const listAvailableToolsApiV1ToolsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListAvailableToolsApiV1ToolsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListAvailableToolsApiV1ToolsGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/tools",
    ...options,
  });
};

/**
 * List Containers
 */
export const listContainersApiV1ContainersGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListContainersApiV1ContainersGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListContainersApiV1ContainersGetResponses,
    ListContainersApiV1ContainersGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/containers",
    ...options,
  });
};

/**
 * Create Container
 */
export const createContainerApiV1ContainersPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateContainerApiV1ContainersPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateContainerApiV1ContainersPostResponses,
    CreateContainerApiV1ContainersPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/containers",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Container
 */
export const deleteContainerApiV1ContainersContainerIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteContainerApiV1ContainersContainerIdDeleteData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).delete<
    DeleteContainerApiV1ContainersContainerIdDeleteResponses,
    DeleteContainerApiV1ContainersContainerIdDeleteErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/containers/{container_id}",
    ...options,
  });
};

/**
 * Get Container By Id
 */
export const getContainerByIdApiV1ContainersContainerIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetContainerByIdApiV1ContainersContainerIdGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).get<
    GetContainerByIdApiV1ContainersContainerIdGetResponses,
    GetContainerByIdApiV1ContainersContainerIdGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/containers/{container_id}",
    ...options,
  });
};

/**
 * Unbind Agent Container
 */
export const unbindAgentContainerApiV1ContainersAgentsAgentKeyContainerDelete =
  <ThrowOnError extends boolean = false>(
    options: Options<
      UnbindAgentContainerApiV1ContainersAgentsAgentKeyContainerDeleteData,
      ThrowOnError
    >,
  ) => {
    return (options.client ?? client).delete<
      UnbindAgentContainerApiV1ContainersAgentsAgentKeyContainerDeleteResponses,
      UnbindAgentContainerApiV1ContainersAgentsAgentKeyContainerDeleteErrors,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/api/v1/containers/agents/{agent_key}/container",
      ...options,
    });
  };

/**
 * Bind Agent Container
 */
export const bindAgentContainerApiV1ContainersAgentsAgentKeyContainerPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    BindAgentContainerApiV1ContainersAgentsAgentKeyContainerPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    BindAgentContainerApiV1ContainersAgentsAgentKeyContainerPostResponses,
    BindAgentContainerApiV1ContainersAgentsAgentKeyContainerPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/containers/agents/{agent_key}/container",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Vector Stores
 */
export const listVectorStoresApiV1VectorStoresGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListVectorStoresApiV1VectorStoresGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListVectorStoresApiV1VectorStoresGetResponses,
    ListVectorStoresApiV1VectorStoresGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/vector-stores",
    ...options,
  });
};

/**
 * Create Vector Store
 */
export const createVectorStoreApiV1VectorStoresPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateVectorStoreApiV1VectorStoresPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateVectorStoreApiV1VectorStoresPostResponses,
    CreateVectorStoreApiV1VectorStoresPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/vector-stores",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Vector Store
 */
export const deleteVectorStoreApiV1VectorStoresVectorStoreIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteVectorStoreApiV1VectorStoresVectorStoreIdDeleteData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).delete<
    DeleteVectorStoreApiV1VectorStoresVectorStoreIdDeleteResponses,
    DeleteVectorStoreApiV1VectorStoresVectorStoreIdDeleteErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/vector-stores/{vector_store_id}",
    ...options,
  });
};

/**
 * Get Vector Store
 */
export const getVectorStoreApiV1VectorStoresVectorStoreIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetVectorStoreApiV1VectorStoresVectorStoreIdGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).get<
    GetVectorStoreApiV1VectorStoresVectorStoreIdGetResponses,
    GetVectorStoreApiV1VectorStoresVectorStoreIdGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/vector-stores/{vector_store_id}",
    ...options,
  });
};

/**
 * List Files
 */
export const listFilesApiV1VectorStoresVectorStoreIdFilesGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListFilesApiV1VectorStoresVectorStoreIdFilesGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).get<
    ListFilesApiV1VectorStoresVectorStoreIdFilesGetResponses,
    ListFilesApiV1VectorStoresVectorStoreIdFilesGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/vector-stores/{vector_store_id}/files",
    ...options,
  });
};

/**
 * Attach File
 */
export const attachFileApiV1VectorStoresVectorStoreIdFilesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AttachFileApiV1VectorStoresVectorStoreIdFilesPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    AttachFileApiV1VectorStoresVectorStoreIdFilesPostResponses,
    AttachFileApiV1VectorStoresVectorStoreIdFilesPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/vector-stores/{vector_store_id}/files",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete File
 */
export const deleteFileApiV1VectorStoresVectorStoreIdFilesFileIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteFileApiV1VectorStoresVectorStoreIdFilesFileIdDeleteData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).delete<
    DeleteFileApiV1VectorStoresVectorStoreIdFilesFileIdDeleteResponses,
    DeleteFileApiV1VectorStoresVectorStoreIdFilesFileIdDeleteErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/vector-stores/{vector_store_id}/files/{file_id}",
    ...options,
  });
};

/**
 * Get File
 */
export const getFileApiV1VectorStoresVectorStoreIdFilesFileIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetFileApiV1VectorStoresVectorStoreIdFilesFileIdGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).get<
    GetFileApiV1VectorStoresVectorStoreIdFilesFileIdGetResponses,
    GetFileApiV1VectorStoresVectorStoreIdFilesFileIdGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/vector-stores/{vector_store_id}/files/{file_id}",
    ...options,
  });
};

/**
 * Search Vector Store
 */
export const searchVectorStoreApiV1VectorStoresVectorStoreIdSearchPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    SearchVectorStoreApiV1VectorStoresVectorStoreIdSearchPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    SearchVectorStoreApiV1VectorStoresVectorStoreIdSearchPostResponses,
    SearchVectorStoreApiV1VectorStoresVectorStoreIdSearchPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/vector-stores/{vector_store_id}/search",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Create Presigned Upload
 */
export const createPresignedUploadApiV1StorageObjectsUploadUrlPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreatePresignedUploadApiV1StorageObjectsUploadUrlPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    CreatePresignedUploadApiV1StorageObjectsUploadUrlPostResponses,
    CreatePresignedUploadApiV1StorageObjectsUploadUrlPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/storage/objects/upload-url",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Objects
 */
export const listObjectsApiV1StorageObjectsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListObjectsApiV1StorageObjectsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListObjectsApiV1StorageObjectsGetResponses,
    ListObjectsApiV1StorageObjectsGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/storage/objects",
    ...options,
  });
};

/**
 * Get Download Url
 */
export const getDownloadUrlApiV1StorageObjectsObjectIdDownloadUrlGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetDownloadUrlApiV1StorageObjectsObjectIdDownloadUrlGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).get<
    GetDownloadUrlApiV1StorageObjectsObjectIdDownloadUrlGetResponses,
    GetDownloadUrlApiV1StorageObjectsObjectIdDownloadUrlGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/storage/objects/{object_id}/download-url",
    ...options,
  });
};

/**
 * Delete Object
 */
export const deleteObjectApiV1StorageObjectsObjectIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteObjectApiV1StorageObjectsObjectIdDeleteData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).delete<
    DeleteObjectApiV1StorageObjectsObjectIdDeleteResponses,
    DeleteObjectApiV1StorageObjectsObjectIdDeleteErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/storage/objects/{object_id}",
    ...options,
  });
};

/**
 * Get Platform Status
 *
 * Return the latest platform status snapshot.
 */
export const getPlatformStatusApiV1StatusGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetPlatformStatusApiV1StatusGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetPlatformStatusApiV1StatusGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/v1/status",
    ...options,
  });
};

/**
 * Get Platform Status Rss
 *
 * Return the incident feed as an RSS document.
 */
export const getPlatformStatusRssApiV1StatusRssGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetPlatformStatusRssApiV1StatusRssGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetPlatformStatusRssApiV1StatusRssGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/v1/status/rss",
    ...options,
  });
};

/**
 * List Status Subscriptions
 */
export const listStatusSubscriptionsApiV1StatusSubscriptionsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ListStatusSubscriptionsApiV1StatusSubscriptionsGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    ListStatusSubscriptionsApiV1StatusSubscriptionsGetResponses,
    ListStatusSubscriptionsApiV1StatusSubscriptionsGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/status/subscriptions",
    ...options,
  });
};

/**
 * Create Status Subscription
 */
export const createStatusSubscriptionApiV1StatusSubscriptionsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateStatusSubscriptionApiV1StatusSubscriptionsPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    CreateStatusSubscriptionApiV1StatusSubscriptionsPostResponses,
    CreateStatusSubscriptionApiV1StatusSubscriptionsPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/status/subscriptions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Verify Status Subscription
 */
export const verifyStatusSubscriptionApiV1StatusSubscriptionsVerifyPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    VerifyStatusSubscriptionApiV1StatusSubscriptionsVerifyPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    VerifyStatusSubscriptionApiV1StatusSubscriptionsVerifyPostResponses,
    VerifyStatusSubscriptionApiV1StatusSubscriptionsVerifyPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/status/subscriptions/verify",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Confirm Webhook Challenge
 */
export const confirmWebhookChallengeApiV1StatusSubscriptionsChallengePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ConfirmWebhookChallengeApiV1StatusSubscriptionsChallengePostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    ConfirmWebhookChallengeApiV1StatusSubscriptionsChallengePostResponses,
    ConfirmWebhookChallengeApiV1StatusSubscriptionsChallengePostErrors,
    ThrowOnError
  >({
    url: "/api/v1/status/subscriptions/challenge",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Revoke Status Subscription
 */
export const revokeStatusSubscriptionApiV1StatusSubscriptionsSubscriptionIdDelete =
  <ThrowOnError extends boolean = false>(
    options: Options<
      RevokeStatusSubscriptionApiV1StatusSubscriptionsSubscriptionIdDeleteData,
      ThrowOnError
    >,
  ) => {
    return (options.client ?? client).delete<
      RevokeStatusSubscriptionApiV1StatusSubscriptionsSubscriptionIdDeleteResponses,
      RevokeStatusSubscriptionApiV1StatusSubscriptionsSubscriptionIdDeleteErrors,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/api/v1/status/subscriptions/{subscription_id}",
      ...options,
    });
  };

/**
 * Resend Status Incident
 */
export const resendStatusIncidentApiV1StatusIncidentsIncidentIdResendPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ResendStatusIncidentApiV1StatusIncidentsIncidentIdResendPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    ResendStatusIncidentApiV1StatusIncidentsIncidentIdResendPostResponses,
    ResendStatusIncidentApiV1StatusIncidentsIncidentIdResendPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/status/incidents/{incident_id}/resend",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Platform Status Rss Alias
 *
 * Legacy alias for consumers using /status.rss paths.
 */
export const getPlatformStatusRssAliasApiV1StatusRssGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    GetPlatformStatusRssAliasApiV1StatusRssGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    GetPlatformStatusRssAliasApiV1StatusRssGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/v1/status.rss",
    ...options,
  });
};

/**
 * Get Tenant Settings
 */
export const getTenantSettingsApiV1TenantsSettingsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetTenantSettingsApiV1TenantsSettingsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetTenantSettingsApiV1TenantsSettingsGetResponses,
    GetTenantSettingsApiV1TenantsSettingsGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/tenants/settings",
    ...options,
  });
};

/**
 * Update Tenant Settings
 */
export const updateTenantSettingsApiV1TenantsSettingsPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateTenantSettingsApiV1TenantsSettingsPutData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).put<
    UpdateTenantSettingsApiV1TenantsSettingsPutResponses,
    UpdateTenantSettingsApiV1TenantsSettingsPutErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/tenants/settings",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Billing Plans
 *
 * Return the catalog of available billing plans.
 */
export const listBillingPlansApiV1BillingPlansGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListBillingPlansApiV1BillingPlansGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListBillingPlansApiV1BillingPlansGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/v1/billing/plans",
    ...options,
  });
};

/**
 * Get Tenant Subscription
 *
 * Return the current subscription for a tenant.
 */
export const getTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).get<
    GetTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGetResponses,
    GetTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/billing/tenants/{tenant_id}/subscription",
    ...options,
  });
};

/**
 * Update Subscription
 *
 * Adjust subscription metadata (auto-renew, seats, billing email).
 */
export const updateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatchData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).patch<
    UpdateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatchResponses,
    UpdateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatchErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/billing/tenants/{tenant_id}/subscription",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Start Subscription
 *
 * Provision a new subscription for the tenant.
 */
export const startSubscriptionApiV1BillingTenantsTenantIdSubscriptionPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    StartSubscriptionApiV1BillingTenantsTenantIdSubscriptionPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    StartSubscriptionApiV1BillingTenantsTenantIdSubscriptionPostResponses,
    StartSubscriptionApiV1BillingTenantsTenantIdSubscriptionPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/billing/tenants/{tenant_id}/subscription",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Cancel Subscription
 *
 * Cancel the tenant subscription (immediately or at period end).
 */
export const cancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      CancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPostData,
      ThrowOnError
    >,
  ) => {
    return (options.client ?? client).post<
      CancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPostResponses,
      CancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPostErrors,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/api/v1/billing/tenants/{tenant_id}/subscription/cancel",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  };

/**
 * Record Usage
 *
 * Report metered usage for a tenant subscription.
 */
export const recordUsageApiV1BillingTenantsTenantIdUsagePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RecordUsageApiV1BillingTenantsTenantIdUsagePostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    RecordUsageApiV1BillingTenantsTenantIdUsagePostResponses,
    RecordUsageApiV1BillingTenantsTenantIdUsagePostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/billing/tenants/{tenant_id}/usage",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Billing Events
 *
 * Page through the tenant's historical billing events.
 */
export const listBillingEventsApiV1BillingTenantsTenantIdEventsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListBillingEventsApiV1BillingTenantsTenantIdEventsGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).get<
    ListBillingEventsApiV1BillingTenantsTenantIdEventsGetResponses,
    ListBillingEventsApiV1BillingTenantsTenantIdEventsGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/billing/tenants/{tenant_id}/events",
    ...options,
  });
};

/**
 * Billing Event Stream
 */
export const billingEventStreamApiV1BillingStreamGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<BillingEventStreamApiV1BillingStreamGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    BillingEventStreamApiV1BillingStreamGetResponses,
    BillingEventStreamApiV1BillingStreamGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/billing/stream",
    ...options,
  });
};

/**
 * Apply Test Fixtures
 */
export const applyTestFixturesApiV1TestFixturesApplyPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ApplyTestFixturesApiV1TestFixturesApplyPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    ApplyTestFixturesApiV1TestFixturesApplyPostResponses,
    ApplyTestFixturesApiV1TestFixturesApplyPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/test-fixtures/apply",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Issue Email Verification Token
 */
export const issueEmailVerificationTokenApiV1TestFixturesEmailVerificationTokenPost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      IssueEmailVerificationTokenApiV1TestFixturesEmailVerificationTokenPostData,
      ThrowOnError
    >,
  ) => {
    return (options.client ?? client).post<
      IssueEmailVerificationTokenApiV1TestFixturesEmailVerificationTokenPostResponses,
      IssueEmailVerificationTokenApiV1TestFixturesEmailVerificationTokenPostErrors,
      ThrowOnError
    >({
      url: "/api/v1/test-fixtures/email-verification-token",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  };
