// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AgentChatRequest
 *
 * Request body for initiating or continuing a chat session.
 */
export type AgentChatRequest = {
    /**
     * Message
     *
     * User input message for the agent.
     */
    message: string;
    /**
     * Conversation Id
     *
     * Existing conversation identifier to maintain context.
     */
    conversation_id?: string | null;
    /**
     * Agent Type
     *
     * Optional explicit agent to handle the message.
     */
    agent_type?: string | null;
    /**
     * Context
     *
     * Optional, structured context to pass through.
     */
    context?: {
        [key: string]: unknown;
    } | null;
};

/**
 * AgentChatResponse
 *
 * Response body returned after the agent processes a message.
 */
export type AgentChatResponse = {
    /**
     * Response
     *
     * Natural language reply from the agent.
     */
    response: string;
    /**
     * Conversation Id
     *
     * Conversation identifier.
     */
    conversation_id: string;
    /**
     * Agent Used
     *
     * Agent instance that handled the request.
     */
    agent_used: string;
    /**
     * Handoff Occurred
     *
     * Indicates whether a handoff happened mid-conversation.
     */
    handoff_occurred?: boolean;
    /**
     * Metadata
     *
     * Arbitrary metadata returned by the agent pipeline.
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * AgentStatus
 *
 * Detailed information about a specific agent.
 */
export type AgentStatus = {
    /**
     * Name
     *
     * Agent identifier.
     */
    name: string;
    /**
     * Status
     *
     * Operational status.
     */
    status: 'active' | 'inactive' | 'error';
    /**
     * Last Used
     *
     * Last time the agent was invoked.
     */
    last_used?: string | null;
    /**
     * Total Conversations
     *
     * Total number of conversations handled.
     */
    total_conversations?: number;
};

/**
 * AgentSummary
 *
 * Lightweight representation of an available agent.
 */
export type AgentSummary = {
    /**
     * Name
     *
     * Agent identifier.
     */
    name: string;
    /**
     * Status
     *
     * Health status of the agent.
     */
    status: 'active' | 'inactive' | 'error';
    /**
     * Description
     *
     * Short human-readable description.
     */
    description?: string | null;
};

/**
 * BillingPlanResponse
 */
export type BillingPlanResponse = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Interval
     */
    interval: string;
    /**
     * Interval Count
     */
    interval_count: number;
    /**
     * Price Cents
     */
    price_cents: number;
    /**
     * Currency
     */
    currency: string;
    /**
     * Trial Days
     */
    trial_days?: number | null;
    /**
     * Seat Included
     */
    seat_included?: number | null;
    /**
     * Feature Toggles
     */
    feature_toggles?: {
        [key: string]: boolean;
    };
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Features
     */
    features?: Array<PlanFeatureResponse>;
};

/**
 * CancelSubscriptionRequest
 */
export type CancelSubscriptionRequest = {
    /**
     * Cancel At Period End
     *
     * If true, cancellation occurs at the current period end.
     */
    cancel_at_period_end?: boolean;
};

/**
 * ChatMessage
 *
 * Single conversational message.
 */
export type ChatMessage = {
    /**
     * Role
     *
     * Originator of the message.
     */
    role: 'user' | 'assistant' | 'system';
    /**
     * Content
     *
     * Message body.
     */
    content: string;
    /**
     * Timestamp
     *
     * ISO-8601 timestamp if available.
     */
    timestamp?: string | null;
};

/**
 * ConversationHistory
 *
 * Full detail view of a conversation.
 */
export type ConversationHistory = {
    /**
     * Conversation Id
     *
     * Conversation identifier.
     */
    conversation_id: string;
    /**
     * Messages
     *
     * Complete message history.
     */
    messages: Array<ChatMessage>;
    /**
     * Created At
     *
     * Conversation creation timestamp.
     */
    created_at: string;
    /**
     * Updated At
     *
     * Last update timestamp.
     */
    updated_at: string;
    /**
     * Agent Context
     *
     * Optional agent metadata.
     */
    agent_context?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ConversationSummary
 *
 * Lightweight summary used when listing conversations.
 */
export type ConversationSummary = {
    /**
     * Conversation Id
     *
     * Conversation identifier.
     */
    conversation_id: string;
    /**
     * Message Count
     *
     * Number of messages recorded.
     */
    message_count: number;
    /**
     * Last Message
     *
     * Content preview of the latest message.
     */
    last_message: string;
    /**
     * Created At
     *
     * Creation timestamp.
     */
    created_at: string;
    /**
     * Updated At
     *
     * Last update timestamp.
     */
    updated_at: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 *
 * Health check response payload.
 */
export type HealthResponse = {
    /**
     * Status
     *
     * Service health status.
     */
    status: string;
    /**
     * Timestamp
     *
     * ISO-8601 timestamp of the probe.
     */
    timestamp: string;
    /**
     * Version
     *
     * Semantic version of the service.
     */
    version: string;
    /**
     * Uptime
     *
     * Process uptime in seconds when available.
     */
    uptime?: number | null;
};

/**
 * PlanFeatureResponse
 */
export type PlanFeatureResponse = {
    /**
     * Key
     */
    key: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Hard Limit
     */
    hard_limit?: number | null;
    /**
     * Soft Limit
     */
    soft_limit?: number | null;
    /**
     * Is Metered
     */
    is_metered?: boolean;
};

/**
 * ServiceAccountIssueRequest
 *
 * Request payload for service-account refresh token issuance.
 */
export type ServiceAccountIssueRequest = {
    /**
     * Account
     *
     * Service-account identifier.
     */
    account: string;
    /**
     * Scopes
     *
     * Scopes requested for the service account.
     */
    scopes: Array<string>;
    /**
     * Tenant Id
     *
     * Tenant UUID when required by the service account.
     */
    tenant_id?: string | null;
    /**
     * Lifetime Minutes
     *
     * Optional refresh token lifetime in minutes.
     */
    lifetime_minutes?: number | null;
    /**
     * Fingerprint
     *
     * Optional machine or pipeline identifier for auditing.
     */
    fingerprint?: string | null;
    /**
     * Force
     *
     * Force new token creation even when an active token exists.
     */
    force?: boolean;
};

/**
 * ServiceAccountTokenResponse
 *
 * Response returned after issuing a service-account refresh token.
 */
export type ServiceAccountTokenResponse = {
    /**
     * Refresh Token
     *
     * Minted refresh token for the service account.
     */
    refresh_token: string;
    /**
     * Expires At
     *
     * ISO-8601 expiration timestamp.
     */
    expires_at: string;
    /**
     * Issued At
     *
     * ISO-8601 issuance timestamp.
     */
    issued_at: string;
    /**
     * Scopes
     *
     * Authorized scopes.
     */
    scopes: Array<string>;
    /**
     * Tenant Id
     *
     * Tenant UUID if the account is tenant-scoped.
     */
    tenant_id?: string | null;
    /**
     * Kid
     *
     * Key identifier used to sign the token.
     */
    kid: string;
    /**
     * Account
     *
     * Service-account identifier.
     */
    account: string;
    /**
     * Token Use
     *
     * Token classification (refresh, access, etc.).
     */
    token_use: string;
};

/**
 * StartSubscriptionRequest
 */
export type StartSubscriptionRequest = {
    /**
     * Plan Code
     *
     * Billing plan to activate.
     */
    plan_code: string;
    /**
     * Billing Email
     *
     * Primary billing contact.
     */
    billing_email?: string | null;
    /**
     * Auto Renew
     *
     * Whether the subscription auto-renews.
     */
    auto_renew?: boolean;
    /**
     * Seat Count
     *
     * Optional explicit seat count override.
     */
    seat_count?: number | null;
};

/**
 * SuccessResponse
 *
 * Standard success response envelope.
 */
export type SuccessResponse = {
    /**
     * Success
     *
     * Operation success status flag.
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable summary of the result.
     */
    message: string;
    /**
     * Data
     *
     * Optional payload containing the result.
     */
    data?: unknown | null;
};

/**
 * TenantSubscriptionResponse
 */
export type TenantSubscriptionResponse = {
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Plan Code
     */
    plan_code: string;
    /**
     * Status
     */
    status: string;
    /**
     * Auto Renew
     */
    auto_renew: boolean;
    /**
     * Billing Email
     */
    billing_email: string | null;
    /**
     * Starts At
     */
    starts_at: string;
    /**
     * Current Period Start
     */
    current_period_start?: string | null;
    /**
     * Current Period End
     */
    current_period_end?: string | null;
    /**
     * Trial Ends At
     */
    trial_ends_at?: string | null;
    /**
     * Cancel At
     */
    cancel_at?: string | null;
    /**
     * Seat Count
     */
    seat_count?: number | null;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * UpdateSubscriptionRequest
 */
export type UpdateSubscriptionRequest = {
    /**
     * Auto Renew
     *
     * Toggle auto-renewal.
     */
    auto_renew?: boolean | null;
    /**
     * Billing Email
     *
     * Override billing contact.
     */
    billing_email?: string | null;
    /**
     * Seat Count
     *
     * Adjust allocated seats.
     */
    seat_count?: number | null;
};

/**
 * UsageRecordRequest
 */
export type UsageRecordRequest = {
    /**
     * Feature Key
     *
     * Identifier of the metered feature.
     */
    feature_key: string;
    /**
     * Quantity
     *
     * Units consumed in this report.
     */
    quantity: number;
    /**
     * Idempotency Key
     *
     * Client-provided key to deduplicate usage submissions.
     */
    idempotency_key?: string | null;
    /**
     * Period Start
     *
     * Billing period start (UTC).
     */
    period_start?: string | null;
    /**
     * Period End
     *
     * Billing period end (UTC).
     */
    period_end?: string | null;
};

/**
 * UserLoginRequest
 *
 * Human user login payload.
 */
export type UserLoginRequest = {
    /**
     * Email
     *
     * User email address.
     */
    email: string;
    /**
     * Password
     *
     * Plaintext password to verify.
     */
    password: string;
    /**
     * Tenant Id
     *
     * Tenant UUID when the user belongs to multiple tenants.
     */
    tenant_id?: string | null;
};

/**
 * UserRefreshRequest
 *
 * Refresh session request payload.
 */
export type UserRefreshRequest = {
    /**
     * Refresh Token
     *
     * Previously issued refresh token.
     */
    refresh_token: string;
};

/**
 * UserRegisterRequest
 *
 * Public signup payload used to create a tenant + owner account.
 */
export type UserRegisterRequest = {
    /**
     * Email
     *
     * Primary user email used for login + billing.
     */
    email: string;
    /**
     * Password
     *
     * Password that meets the platform's minimum complexity requirements.
     */
    password: string;
    /**
     * Tenant Name
     *
     * Display name for the tenant.
     */
    tenant_name: string;
    /**
     * Display Name
     *
     * Optional profile display name for the owner account.
     */
    display_name?: string | null;
    /**
     * Plan Code
     *
     * Requested billing plan (defaults to server configuration when omitted).
     */
    plan_code?: string | null;
    /**
     * Trial Days
     *
     * Optional trial duration hint; ignored unless the deployment explicitly allows overrides.
     */
    trial_days?: number | null;
    /**
     * Accept Terms
     *
     * Indicates whether the caller accepted the Terms of Service.
     */
    accept_terms?: boolean;
};

/**
 * UserRegisterResponse
 *
 * Session response returned by /auth/register with tenant metadata.
 */
export type UserRegisterResponse = {
    /**
     * Access Token
     *
     * Signed JWT access token.
     */
    access_token: string;
    /**
     * Refresh Token
     *
     * Signed JWT refresh token.
     */
    refresh_token: string;
    /**
     * Token Type
     *
     * Token type hint for the Authorization header.
     */
    token_type?: string;
    /**
     * Expires At
     *
     * ISO-8601 timestamp when the access token expires.
     */
    expires_at: string;
    /**
     * Refresh Expires At
     *
     * ISO-8601 timestamp when the refresh token expires.
     */
    refresh_expires_at: string;
    /**
     * Kid
     *
     * Key identifier used to sign the access token.
     */
    kid: string;
    /**
     * Refresh Kid
     *
     * Key identifier used to sign the refresh token.
     */
    refresh_kid: string;
    /**
     * Scopes
     *
     * Scopes granted to the session.
     */
    scopes: Array<string>;
    /**
     * Tenant Id
     *
     * Tenant identifier tied to the session.
     */
    tenant_id: string;
    /**
     * User Id
     *
     * Authenticated user identifier.
     */
    user_id: string;
    /**
     * Tenant Slug
     *
     * URL-safe slug generated for the tenant.
     */
    tenant_slug: string;
};

/**
 * UserSessionResponse
 *
 * Bearer credential pair returned after login or refresh.
 */
export type UserSessionResponse = {
    /**
     * Access Token
     *
     * Signed JWT access token.
     */
    access_token: string;
    /**
     * Refresh Token
     *
     * Signed JWT refresh token.
     */
    refresh_token: string;
    /**
     * Token Type
     *
     * Token type hint for the Authorization header.
     */
    token_type?: string;
    /**
     * Expires At
     *
     * ISO-8601 timestamp when the access token expires.
     */
    expires_at: string;
    /**
     * Refresh Expires At
     *
     * ISO-8601 timestamp when the refresh token expires.
     */
    refresh_expires_at: string;
    /**
     * Kid
     *
     * Key identifier used to sign the access token.
     */
    kid: string;
    /**
     * Refresh Kid
     *
     * Key identifier used to sign the refresh token.
     */
    refresh_kid: string;
    /**
     * Scopes
     *
     * Scopes granted to the session.
     */
    scopes: Array<string>;
    /**
     * Tenant Id
     *
     * Tenant identifier tied to the session.
     */
    tenant_id: string;
    /**
     * User Id
     *
     * Authenticated user identifier.
     */
    user_id: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthCheckHealthGetResponse = HealthCheckHealthGetResponses[keyof HealthCheckHealthGetResponses];

export type ReadinessCheckHealthReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type ReadinessCheckHealthReadyGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type ReadinessCheckHealthReadyGetResponse = ReadinessCheckHealthReadyGetResponses[keyof ReadinessCheckHealthReadyGetResponses];

export type HandleStripeWebhookWebhooksStripePostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/webhooks/stripe';
};

export type HandleStripeWebhookWebhooksStripePostResponses = {
    /**
     * Response Handle Stripe Webhook Webhooks Stripe Post
     *
     * Successful Response
     */
    202: {
        [key: string]: boolean;
    };
};

export type HandleStripeWebhookWebhooksStripePostResponse = HandleStripeWebhookWebhooksStripePostResponses[keyof HandleStripeWebhookWebhooksStripePostResponses];

export type RegisterTenantApiV1AuthRegisterPostData = {
    body: UserRegisterRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterTenantApiV1AuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterTenantApiV1AuthRegisterPostError = RegisterTenantApiV1AuthRegisterPostErrors[keyof RegisterTenantApiV1AuthRegisterPostErrors];

export type RegisterTenantApiV1AuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: UserRegisterResponse;
};

export type RegisterTenantApiV1AuthRegisterPostResponse = RegisterTenantApiV1AuthRegisterPostResponses[keyof RegisterTenantApiV1AuthRegisterPostResponses];

export type LoginForAccessTokenApiV1AuthTokenPostData = {
    body: UserLoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/token';
};

export type LoginForAccessTokenApiV1AuthTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginForAccessTokenApiV1AuthTokenPostError = LoginForAccessTokenApiV1AuthTokenPostErrors[keyof LoginForAccessTokenApiV1AuthTokenPostErrors];

export type LoginForAccessTokenApiV1AuthTokenPostResponses = {
    /**
     * Successful Response
     */
    200: UserSessionResponse;
};

export type LoginForAccessTokenApiV1AuthTokenPostResponse = LoginForAccessTokenApiV1AuthTokenPostResponses[keyof LoginForAccessTokenApiV1AuthTokenPostResponses];

export type RefreshAccessTokenApiV1AuthRefreshPostData = {
    body: UserRefreshRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type RefreshAccessTokenApiV1AuthRefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshAccessTokenApiV1AuthRefreshPostError = RefreshAccessTokenApiV1AuthRefreshPostErrors[keyof RefreshAccessTokenApiV1AuthRefreshPostErrors];

export type RefreshAccessTokenApiV1AuthRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: UserSessionResponse;
};

export type RefreshAccessTokenApiV1AuthRefreshPostResponse = RefreshAccessTokenApiV1AuthRefreshPostResponses[keyof RefreshAccessTokenApiV1AuthRefreshPostResponses];

export type GetCurrentUserInfoApiV1AuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type GetCurrentUserInfoApiV1AuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponse;
};

export type GetCurrentUserInfoApiV1AuthMeGetResponse = GetCurrentUserInfoApiV1AuthMeGetResponses[keyof GetCurrentUserInfoApiV1AuthMeGetResponses];

export type IssueServiceAccountTokenApiV1AuthServiceAccountsIssuePostData = {
    body: ServiceAccountIssueRequest;
    headers: {
        /**
         * Authorization
         */
        Authorization: string;
        /**
         * X-Vault-Payload
         */
        'X-Vault-Payload'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/service-accounts/issue';
};

export type IssueServiceAccountTokenApiV1AuthServiceAccountsIssuePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IssueServiceAccountTokenApiV1AuthServiceAccountsIssuePostError = IssueServiceAccountTokenApiV1AuthServiceAccountsIssuePostErrors[keyof IssueServiceAccountTokenApiV1AuthServiceAccountsIssuePostErrors];

export type IssueServiceAccountTokenApiV1AuthServiceAccountsIssuePostResponses = {
    /**
     * Successful Response
     */
    201: ServiceAccountTokenResponse;
};

export type IssueServiceAccountTokenApiV1AuthServiceAccountsIssuePostResponse = IssueServiceAccountTokenApiV1AuthServiceAccountsIssuePostResponses[keyof IssueServiceAccountTokenApiV1AuthServiceAccountsIssuePostResponses];

export type ChatWithAgentApiV1ChatPostData = {
    body: AgentChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/chat';
};

export type ChatWithAgentApiV1ChatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatWithAgentApiV1ChatPostError = ChatWithAgentApiV1ChatPostErrors[keyof ChatWithAgentApiV1ChatPostErrors];

export type ChatWithAgentApiV1ChatPostResponses = {
    /**
     * Successful Response
     */
    200: AgentChatResponse;
};

export type ChatWithAgentApiV1ChatPostResponse = ChatWithAgentApiV1ChatPostResponses[keyof ChatWithAgentApiV1ChatPostResponses];

export type StreamChatWithAgentApiV1ChatStreamPostData = {
    body: AgentChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/chat/stream';
};

export type StreamChatWithAgentApiV1ChatStreamPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamChatWithAgentApiV1ChatStreamPostError = StreamChatWithAgentApiV1ChatStreamPostErrors[keyof StreamChatWithAgentApiV1ChatStreamPostErrors];

export type StreamChatWithAgentApiV1ChatStreamPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListAvailableAgentsApiV1AgentsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/agents';
};

export type ListAvailableAgentsApiV1AgentsGetResponses = {
    /**
     * Response List Available Agents Api V1 Agents Get
     *
     * Successful Response
     */
    200: Array<AgentSummary>;
};

export type ListAvailableAgentsApiV1AgentsGetResponse = ListAvailableAgentsApiV1AgentsGetResponses[keyof ListAvailableAgentsApiV1AgentsGetResponses];

export type GetAgentStatusApiV1AgentsAgentNameStatusGetData = {
    body?: never;
    path: {
        /**
         * Agent Name
         */
        agent_name: string;
    };
    query?: never;
    url: '/api/v1/agents/{agent_name}/status';
};

export type GetAgentStatusApiV1AgentsAgentNameStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAgentStatusApiV1AgentsAgentNameStatusGetError = GetAgentStatusApiV1AgentsAgentNameStatusGetErrors[keyof GetAgentStatusApiV1AgentsAgentNameStatusGetErrors];

export type GetAgentStatusApiV1AgentsAgentNameStatusGetResponses = {
    /**
     * Successful Response
     */
    200: AgentStatus;
};

export type GetAgentStatusApiV1AgentsAgentNameStatusGetResponse = GetAgentStatusApiV1AgentsAgentNameStatusGetResponses[keyof GetAgentStatusApiV1AgentsAgentNameStatusGetResponses];

export type ListConversationsApiV1ConversationsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/conversations';
};

export type ListConversationsApiV1ConversationsGetResponses = {
    /**
     * Response List Conversations Api V1 Conversations Get
     *
     * Successful Response
     */
    200: Array<ConversationSummary>;
};

export type ListConversationsApiV1ConversationsGetResponse = ListConversationsApiV1ConversationsGetResponses[keyof ListConversationsApiV1ConversationsGetResponses];

export type DeleteConversationApiV1ConversationsConversationIdDeleteData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/conversations/{conversation_id}';
};

export type DeleteConversationApiV1ConversationsConversationIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteConversationApiV1ConversationsConversationIdDeleteError = DeleteConversationApiV1ConversationsConversationIdDeleteErrors[keyof DeleteConversationApiV1ConversationsConversationIdDeleteErrors];

export type DeleteConversationApiV1ConversationsConversationIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteConversationApiV1ConversationsConversationIdDeleteResponse = DeleteConversationApiV1ConversationsConversationIdDeleteResponses[keyof DeleteConversationApiV1ConversationsConversationIdDeleteResponses];

export type GetConversationApiV1ConversationsConversationIdGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/conversations/{conversation_id}';
};

export type GetConversationApiV1ConversationsConversationIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConversationApiV1ConversationsConversationIdGetError = GetConversationApiV1ConversationsConversationIdGetErrors[keyof GetConversationApiV1ConversationsConversationIdGetErrors];

export type GetConversationApiV1ConversationsConversationIdGetResponses = {
    /**
     * Successful Response
     */
    200: ConversationHistory;
};

export type GetConversationApiV1ConversationsConversationIdGetResponse = GetConversationApiV1ConversationsConversationIdGetResponses[keyof GetConversationApiV1ConversationsConversationIdGetResponses];

export type ListAvailableToolsApiV1ToolsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tools';
};

export type ListAvailableToolsApiV1ToolsGetResponses = {
    /**
     * Response List Available Tools Api V1 Tools Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ListAvailableToolsApiV1ToolsGetResponse = ListAvailableToolsApiV1ToolsGetResponses[keyof ListAvailableToolsApiV1ToolsGetResponses];

export type ListBillingPlansApiV1BillingPlansGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/billing/plans';
};

export type ListBillingPlansApiV1BillingPlansGetResponses = {
    /**
     * Response List Billing Plans Api V1 Billing Plans Get
     *
     * Successful Response
     */
    200: Array<BillingPlanResponse>;
};

export type ListBillingPlansApiV1BillingPlansGetResponse = ListBillingPlansApiV1BillingPlansGetResponses[keyof ListBillingPlansApiV1BillingPlansGetResponses];

export type GetTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGetData = {
    body?: never;
    headers?: {
        /**
         * X-Tenant-Id
         */
        'X-Tenant-Id'?: string | null;
        /**
         * X-Tenant-Role
         */
        'X-Tenant-Role'?: string | null;
    };
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: never;
    url: '/api/v1/billing/tenants/{tenant_id}/subscription';
};

export type GetTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGetError = GetTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGetErrors[keyof GetTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGetErrors];

export type GetTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGetResponses = {
    /**
     * Successful Response
     */
    200: TenantSubscriptionResponse;
};

export type GetTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGetResponse = GetTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGetResponses[keyof GetTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGetResponses];

export type UpdateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatchData = {
    body: UpdateSubscriptionRequest;
    headers?: {
        /**
         * X-Tenant-Id
         */
        'X-Tenant-Id'?: string | null;
        /**
         * X-Tenant-Role
         */
        'X-Tenant-Role'?: string | null;
    };
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: never;
    url: '/api/v1/billing/tenants/{tenant_id}/subscription';
};

export type UpdateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatchError = UpdateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatchErrors[keyof UpdateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatchErrors];

export type UpdateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatchResponses = {
    /**
     * Successful Response
     */
    200: TenantSubscriptionResponse;
};

export type UpdateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatchResponse = UpdateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatchResponses[keyof UpdateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatchResponses];

export type StartSubscriptionApiV1BillingTenantsTenantIdSubscriptionPostData = {
    body: StartSubscriptionRequest;
    headers?: {
        /**
         * X-Tenant-Id
         */
        'X-Tenant-Id'?: string | null;
        /**
         * X-Tenant-Role
         */
        'X-Tenant-Role'?: string | null;
    };
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: never;
    url: '/api/v1/billing/tenants/{tenant_id}/subscription';
};

export type StartSubscriptionApiV1BillingTenantsTenantIdSubscriptionPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartSubscriptionApiV1BillingTenantsTenantIdSubscriptionPostError = StartSubscriptionApiV1BillingTenantsTenantIdSubscriptionPostErrors[keyof StartSubscriptionApiV1BillingTenantsTenantIdSubscriptionPostErrors];

export type StartSubscriptionApiV1BillingTenantsTenantIdSubscriptionPostResponses = {
    /**
     * Successful Response
     */
    201: TenantSubscriptionResponse;
};

export type StartSubscriptionApiV1BillingTenantsTenantIdSubscriptionPostResponse = StartSubscriptionApiV1BillingTenantsTenantIdSubscriptionPostResponses[keyof StartSubscriptionApiV1BillingTenantsTenantIdSubscriptionPostResponses];

export type CancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPostData = {
    body: CancelSubscriptionRequest;
    headers?: {
        /**
         * X-Tenant-Id
         */
        'X-Tenant-Id'?: string | null;
        /**
         * X-Tenant-Role
         */
        'X-Tenant-Role'?: string | null;
    };
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: never;
    url: '/api/v1/billing/tenants/{tenant_id}/subscription/cancel';
};

export type CancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPostError = CancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPostErrors[keyof CancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPostErrors];

export type CancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPostResponses = {
    /**
     * Successful Response
     */
    200: TenantSubscriptionResponse;
};

export type CancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPostResponse = CancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPostResponses[keyof CancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPostResponses];

export type RecordUsageApiV1BillingTenantsTenantIdUsagePostData = {
    body: UsageRecordRequest;
    headers?: {
        /**
         * X-Tenant-Id
         */
        'X-Tenant-Id'?: string | null;
        /**
         * X-Tenant-Role
         */
        'X-Tenant-Role'?: string | null;
    };
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: never;
    url: '/api/v1/billing/tenants/{tenant_id}/usage';
};

export type RecordUsageApiV1BillingTenantsTenantIdUsagePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecordUsageApiV1BillingTenantsTenantIdUsagePostError = RecordUsageApiV1BillingTenantsTenantIdUsagePostErrors[keyof RecordUsageApiV1BillingTenantsTenantIdUsagePostErrors];

export type RecordUsageApiV1BillingTenantsTenantIdUsagePostResponses = {
    /**
     * Successful Response
     */
    202: SuccessResponse;
};

export type RecordUsageApiV1BillingTenantsTenantIdUsagePostResponse = RecordUsageApiV1BillingTenantsTenantIdUsagePostResponses[keyof RecordUsageApiV1BillingTenantsTenantIdUsagePostResponses];

export type BillingEventStreamApiV1BillingStreamGetData = {
    body?: never;
    headers?: {
        /**
         * X-Tenant-Id
         */
        'X-Tenant-Id'?: string | null;
        /**
         * X-Tenant-Role
         */
        'X-Tenant-Role'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/billing/stream';
};

export type BillingEventStreamApiV1BillingStreamGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BillingEventStreamApiV1BillingStreamGetError = BillingEventStreamApiV1BillingStreamGetErrors[keyof BillingEventStreamApiV1BillingStreamGetErrors];

export type BillingEventStreamApiV1BillingStreamGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
