// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AgentChatRequest
 *
 * Request body for initiating or continuing a chat session.
 */
export type AgentChatRequest = {
    /**
     * Message
     *
     * User input message for the agent.
     */
    message: string;
    /**
     * Conversation Id
     *
     * Existing conversation identifier to maintain context.
     */
    conversation_id?: string | null;
    /**
     * Agent Type
     *
     * Optional explicit agent to handle the message.
     */
    agent_type?: string | null;
    /**
     * Context
     *
     * Optional, structured context to pass through.
     */
    context?: {
        [key: string]: unknown;
    } | null;
};

/**
 * AgentChatResponse
 *
 * Response body returned after the agent processes a message.
 */
export type AgentChatResponse = {
    /**
     * Response
     *
     * Natural language reply from the agent.
     */
    response: string;
    /**
     * Conversation Id
     *
     * Conversation identifier.
     */
    conversation_id: string;
    /**
     * Agent Used
     *
     * Agent instance that handled the request.
     */
    agent_used: string;
    /**
     * Handoff Occurred
     *
     * Indicates whether a handoff happened mid-conversation.
     */
    handoff_occurred?: boolean;
    /**
     * Metadata
     *
     * Arbitrary metadata returned by the agent pipeline.
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * AgentStatus
 *
 * Detailed information about a specific agent.
 */
export type AgentStatus = {
    /**
     * Name
     *
     * Agent identifier.
     */
    name: string;
    /**
     * Status
     *
     * Operational status.
     */
    status: 'active' | 'inactive' | 'error';
    /**
     * Last Used
     *
     * Last time the agent was invoked.
     */
    last_used?: string | null;
    /**
     * Total Conversations
     *
     * Total number of conversations handled.
     */
    total_conversations?: number;
};

/**
 * AgentSummary
 *
 * Lightweight representation of an available agent.
 */
export type AgentSummary = {
    /**
     * Name
     *
     * Agent identifier.
     */
    name: string;
    /**
     * Status
     *
     * Health status of the agent.
     */
    status: 'active' | 'inactive' | 'error';
    /**
     * Description
     *
     * Short human-readable description.
     */
    description?: string | null;
};

/**
 * BillingContactModel
 */
export type BillingContactModel = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Role
     */
    role?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Notify Billing
     */
    notify_billing?: boolean;
};

/**
 * BillingEventHistoryResponse
 */
export type BillingEventHistoryResponse = {
    /**
     * Items
     */
    items?: Array<BillingEventResponse>;
    /**
     * Next Cursor
     *
     * Opaque cursor for the next page. Null when no additional events exist.
     */
    next_cursor?: string | null;
};

/**
 * BillingEventInvoiceResponse
 */
export type BillingEventInvoiceResponse = {
    /**
     * Invoice Id
     */
    invoice_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Amount Due Cents
     */
    amount_due_cents: number;
    /**
     * Currency
     */
    currency: string;
    /**
     * Billing Reason
     */
    billing_reason?: string | null;
    /**
     * Hosted Invoice Url
     */
    hosted_invoice_url?: string | null;
    /**
     * Collection Method
     */
    collection_method?: string | null;
    /**
     * Period Start
     */
    period_start?: string | null;
    /**
     * Period End
     */
    period_end?: string | null;
};

/**
 * BillingEventResponse
 */
export type BillingEventResponse = {
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Event Type
     */
    event_type: string;
    /**
     * Stripe Event Id
     */
    stripe_event_id: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Summary
     */
    summary?: string | null;
    /**
     * Status
     */
    status: string;
    subscription?: BillingEventSubscriptionResponse | null;
    invoice?: BillingEventInvoiceResponse | null;
    /**
     * Usage
     */
    usage?: Array<BillingEventUsageResponse>;
};

/**
 * BillingEventSubscriptionResponse
 */
export type BillingEventSubscriptionResponse = {
    /**
     * Plan Code
     */
    plan_code: string;
    /**
     * Status
     */
    status: string;
    /**
     * Seat Count
     */
    seat_count?: number | null;
    /**
     * Auto Renew
     */
    auto_renew: boolean;
    /**
     * Current Period Start
     */
    current_period_start?: string | null;
    /**
     * Current Period End
     */
    current_period_end?: string | null;
    /**
     * Trial Ends At
     */
    trial_ends_at?: string | null;
    /**
     * Cancel At
     */
    cancel_at?: string | null;
};

/**
 * BillingEventUsageResponse
 */
export type BillingEventUsageResponse = {
    /**
     * Feature Key
     */
    feature_key: string;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Period Start
     */
    period_start?: string | null;
    /**
     * Period End
     */
    period_end?: string | null;
    /**
     * Amount Cents
     */
    amount_cents?: number | null;
};

/**
 * BillingPlanResponse
 */
export type BillingPlanResponse = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Interval
     */
    interval: string;
    /**
     * Interval Count
     */
    interval_count: number;
    /**
     * Price Cents
     */
    price_cents: number;
    /**
     * Currency
     */
    currency: string;
    /**
     * Trial Days
     */
    trial_days?: number | null;
    /**
     * Seat Included
     */
    seat_included?: number | null;
    /**
     * Feature Toggles
     */
    feature_toggles?: {
        [key: string]: boolean;
    };
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Features
     */
    features?: Array<PlanFeatureResponse>;
};

/**
 * BrowserServiceAccountIssueRequest
 *
 * Browser-initiated issuance request with justification.
 */
export type BrowserServiceAccountIssueRequest = {
    /**
     * Account
     *
     * Service-account identifier.
     */
    account: string;
    /**
     * Scopes
     *
     * Scopes requested for the service account.
     */
    scopes: Array<string>;
    /**
     * Tenant Id
     *
     * Tenant UUID when required by the service account.
     */
    tenant_id?: string | null;
    /**
     * Lifetime Minutes
     *
     * Optional refresh token lifetime in minutes.
     */
    lifetime_minutes?: number | null;
    /**
     * Fingerprint
     *
     * Optional machine or pipeline identifier for auditing.
     */
    fingerprint?: string | null;
    /**
     * Force
     *
     * Force new token creation even when an active token exists.
     */
    force?: boolean;
    /**
     * Reason
     *
     * Human-readable justification for auditing.
     */
    reason: string;
};

/**
 * CancelSubscriptionRequest
 */
export type CancelSubscriptionRequest = {
    /**
     * Cancel At Period End
     *
     * If true, cancellation occurs at the current period end.
     */
    cancel_at_period_end?: boolean;
};

/**
 * ChatMessage
 *
 * Single conversational message.
 */
export type ChatMessage = {
    /**
     * Role
     *
     * Originator of the message.
     */
    role: 'user' | 'assistant' | 'system';
    /**
     * Content
     *
     * Message body.
     */
    content: string;
    /**
     * Timestamp
     *
     * ISO-8601 timestamp if available.
     */
    timestamp?: string | null;
};

/**
 * ConversationHistory
 *
 * Full detail view of a conversation.
 */
export type ConversationHistory = {
    /**
     * Conversation Id
     *
     * Conversation identifier.
     */
    conversation_id: string;
    /**
     * Messages
     *
     * Complete message history.
     */
    messages: Array<ChatMessage>;
    /**
     * Created At
     *
     * Conversation creation timestamp.
     */
    created_at: string;
    /**
     * Updated At
     *
     * Last update timestamp.
     */
    updated_at: string;
    /**
     * Agent Context
     *
     * Optional agent metadata.
     */
    agent_context?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ConversationSummary
 *
 * Lightweight summary used when listing conversations.
 */
export type ConversationSummary = {
    /**
     * Conversation Id
     *
     * Conversation identifier.
     */
    conversation_id: string;
    /**
     * Message Count
     *
     * Number of messages recorded.
     */
    message_count: number;
    /**
     * Last Message
     *
     * Content preview of the latest message.
     */
    last_message: string;
    /**
     * Created At
     *
     * Creation timestamp.
     */
    created_at: string;
    /**
     * Updated At
     *
     * Last update timestamp.
     */
    updated_at: string;
};

/**
 * EmailVerificationConfirmRequest
 *
 * Payload for confirming the email verification token.
 */
export type EmailVerificationConfirmRequest = {
    /**
     * Token
     *
     * Verification token delivered via email.
     */
    token: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 *
 * Health check response payload.
 */
export type HealthResponse = {
    /**
     * Status
     *
     * Service health status.
     */
    status: string;
    /**
     * Timestamp
     *
     * ISO-8601 timestamp of the probe.
     */
    timestamp: string;
    /**
     * Version
     *
     * Semantic version of the service.
     */
    version: string;
    /**
     * Uptime
     *
     * Process uptime in seconds when available.
     */
    uptime?: number | null;
};

/**
 * IncidentSchema
 */
export type IncidentSchema = {
    /**
     * Incident Id
     *
     * Internal incident identifier.
     */
    incident_id: string;
    /**
     * Service
     *
     * Impacted service name.
     */
    service: string;
    /**
     * Occurred At
     *
     * When the incident was recorded.
     */
    occurred_at: string;
    /**
     * Impact
     *
     * External-facing description of the impact.
     */
    impact: string;
    /**
     * State
     *
     * Current incident lifecycle state.
     */
    state: string;
};

/**
 * PasswordChangeRequest
 *
 * Self-service password change payload.
 */
export type PasswordChangeRequest = {
    /**
     * Current Password
     *
     * Current password for verification.
     */
    current_password: string;
    /**
     * New Password
     *
     * New password that satisfies platform policy.
     */
    new_password: string;
};

/**
 * PasswordForgotRequest
 *
 * Initiate a password reset email.
 */
export type PasswordForgotRequest = {
    /**
     * Email
     *
     * Email address associated with the account.
     */
    email: string;
};

/**
 * PasswordResetConfirmRequest
 *
 * Redeem a password reset token to set a new password.
 */
export type PasswordResetConfirmRequest = {
    /**
     * Token
     *
     * Password reset token from email.
     */
    token: string;
    /**
     * New Password
     *
     * Replacement password that satisfies platform policy.
     */
    new_password: string;
};

/**
 * PasswordResetRequest
 *
 * Admin-initiated password reset payload.
 */
export type PasswordResetRequest = {
    /**
     * User Id
     *
     * Target user identifier.
     */
    user_id: string;
    /**
     * New Password
     *
     * Replacement password that satisfies platform policy.
     */
    new_password: string;
};

/**
 * PlanFeatureResponse
 */
export type PlanFeatureResponse = {
    /**
     * Key
     */
    key: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Hard Limit
     */
    hard_limit?: number | null;
    /**
     * Soft Limit
     */
    soft_limit?: number | null;
    /**
     * Is Metered
     */
    is_metered?: boolean;
};

/**
 * PlatformStatusResponse
 */
export type PlatformStatusResponse = {
    /**
     * Generated At
     *
     * Server-side generation timestamp for the snapshot.
     */
    generated_at: string;
    overview: StatusOverviewSchema;
    /**
     * Services
     */
    services: Array<ServiceStatusSchema>;
    /**
     * Incidents
     */
    incidents: Array<IncidentSchema>;
    /**
     * Uptime Metrics
     */
    uptime_metrics: Array<UptimeMetricSchema>;
};

/**
 * ServiceAccountIssueRequest
 *
 * Request payload for service-account refresh token issuance.
 */
export type ServiceAccountIssueRequest = {
    /**
     * Account
     *
     * Service-account identifier.
     */
    account: string;
    /**
     * Scopes
     *
     * Scopes requested for the service account.
     */
    scopes: Array<string>;
    /**
     * Tenant Id
     *
     * Tenant UUID when required by the service account.
     */
    tenant_id?: string | null;
    /**
     * Lifetime Minutes
     *
     * Optional refresh token lifetime in minutes.
     */
    lifetime_minutes?: number | null;
    /**
     * Fingerprint
     *
     * Optional machine or pipeline identifier for auditing.
     */
    fingerprint?: string | null;
    /**
     * Force
     *
     * Force new token creation even when an active token exists.
     */
    force?: boolean;
};

/**
 * ServiceAccountTokenItem
 *
 * List view representation of a service-account refresh token.
 */
export type ServiceAccountTokenItem = {
    /**
     * Jti
     *
     * Refresh token unique identifier (JWT jti).
     */
    jti: string;
    /**
     * Account
     *
     * Service-account identifier owning the token.
     */
    account: string;
    /**
     * Tenant Id
     *
     * Tenant UUID when the token is tenant-scoped.
     */
    tenant_id?: string | null;
    /**
     * Scopes
     *
     * Authorized scopes.
     */
    scopes: Array<string>;
    /**
     * Issued At
     *
     * Issuance timestamp.
     */
    issued_at: string;
    /**
     * Expires At
     *
     * Expiration timestamp.
     */
    expires_at: string;
    /**
     * Revoked At
     *
     * Revocation timestamp, if applicable.
     */
    revoked_at: string | null;
    /**
     * Revoked Reason
     *
     * Optional reason recorded during revocation.
     */
    revoked_reason?: string | null;
    /**
     * Fingerprint
     *
     * Caller-provided fingerprint for auditing.
     */
    fingerprint?: string | null;
    /**
     * Signing Kid
     *
     * Key identifier used to sign the refresh token.
     */
    signing_kid: string;
};

/**
 * ServiceAccountTokenListResponse
 *
 * Paginated response for service-account token listings.
 */
export type ServiceAccountTokenListResponse = {
    /**
     * Items
     *
     * Current page of results.
     */
    items: Array<ServiceAccountTokenItem>;
    /**
     * Total
     *
     * Total number of matching tokens across all pages.
     */
    total: number;
    /**
     * Limit
     *
     * Requested page size.
     */
    limit: number;
    /**
     * Offset
     *
     * Requested offset.
     */
    offset: number;
};

/**
 * ServiceAccountTokenResponse
 *
 * Response returned after issuing a service-account refresh token.
 */
export type ServiceAccountTokenResponse = {
    /**
     * Refresh Token
     *
     * Minted refresh token for the service account.
     */
    refresh_token: string;
    /**
     * Expires At
     *
     * ISO-8601 expiration timestamp.
     */
    expires_at: string;
    /**
     * Issued At
     *
     * ISO-8601 issuance timestamp.
     */
    issued_at: string;
    /**
     * Scopes
     *
     * Authorized scopes attached to the token.
     */
    scopes: Array<string>;
    /**
     * Tenant Id
     *
     * Tenant UUID if the account is tenant-scoped.
     */
    tenant_id?: string | null;
    /**
     * Kid
     *
     * Key identifier used to sign the token.
     */
    kid: string;
    /**
     * Account
     *
     * Service-account identifier.
     */
    account: string;
    /**
     * Token Use
     *
     * Token classification (refresh, access, etc.).
     */
    token_use: string;
    /**
     * Session Id
     *
     * Optional session identifier when linked to a human session.
     */
    session_id?: string | null;
};

/**
 * ServiceAccountTokenRevokeRequest
 *
 * Payload for revoking a service-account refresh token.
 */
export type ServiceAccountTokenRevokeRequest = {
    /**
     * Reason
     *
     * Human-readable explanation for auditing (required for operators).
     */
    reason?: string | null;
};

/**
 * ServiceAccountTokenStatus
 */
export type ServiceAccountTokenStatus = 'active' | 'revoked' | 'all';

/**
 * ServiceStatusSchema
 */
export type ServiceStatusSchema = {
    /**
     * Name
     *
     * Service or subsystem name.
     */
    name: string;
    /**
     * Status
     *
     * Operational status label.
     */
    status: string;
    /**
     * Description
     *
     * Short explanation of the service scope.
     */
    description: string;
    /**
     * Owner
     *
     * Team responsible for the service.
     */
    owner: string;
    /**
     * Last Incident At
     *
     * Timestamp of the most recent incident involving the service.
     */
    last_incident_at?: string | null;
};

/**
 * SessionClientInfo
 *
 * Details about the client/browser reported for a session.
 */
export type SessionClientInfo = {
    /**
     * Platform
     *
     * Operating system/platform hint derived from the user-agent.
     */
    platform?: string | null;
    /**
     * Browser
     *
     * Browser family detected from the user-agent.
     */
    browser?: string | null;
    /**
     * Device
     *
     * Device class (desktop, mobile, tablet, bot).
     */
    device?: string | null;
    /**
     * User Agent
     *
     * Raw user-agent string captured during login/refresh.
     */
    user_agent?: string | null;
};

/**
 * SessionLocationInfo
 *
 * Approximate geolocation information for a session.
 */
export type SessionLocationInfo = {
    /**
     * City
     *
     * City derived from GeoIP (if available).
     */
    city?: string | null;
    /**
     * Region
     *
     * Region/subdivision derived from GeoIP.
     */
    region?: string | null;
    /**
     * Country
     *
     * Country code derived from GeoIP.
     */
    country?: string | null;
};

/**
 * SignupAccessPolicyResponse
 */
export type SignupAccessPolicyResponse = {
    /**
     * Policy
     *
     * Active signup access policy.
     */
    policy: string;
    /**
     * Invite Required
     *
     * Indicates whether an invite token is required.
     */
    invite_required: boolean;
    /**
     * Request Access Enabled
     *
     * Whether deployments expose the access-request workflow.
     */
    request_access_enabled: boolean;
};

/**
 * SignupInviteIssueRequest
 */
export type SignupInviteIssueRequest = {
    /**
     * Invited Email
     *
     * Optional email restriction for the invite.
     */
    invited_email?: string | null;
    /**
     * Max Redemptions
     *
     * Maximum number of tenants that can redeem the invite.
     */
    max_redemptions?: number;
    /**
     * Expires In Hours
     *
     * Invite expiry window expressed in hours.
     */
    expires_in_hours?: number | null;
    /**
     * Note
     *
     * Operator note stored alongside the invite.
     */
    note?: string | null;
    /**
     * Signup Request Id
     *
     * Associate the invite with a previously submitted signup request.
     */
    signup_request_id?: string | null;
};

/**
 * SignupInviteIssueResponse
 */
export type SignupInviteIssueResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Token Hint
     */
    token_hint: string;
    /**
     * Invited Email
     */
    invited_email?: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Max Redemptions
     */
    max_redemptions: number;
    /**
     * Redeemed Count
     */
    redeemed_count: number;
    /**
     * Expires At
     */
    expires_at?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Signup Request Id
     */
    signup_request_id?: string | null;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Invite Token
     *
     * Plaintext invite token (only returned once).
     */
    invite_token: string;
};

/**
 * SignupInviteListResponse
 */
export type SignupInviteListResponse = {
    /**
     * Invites
     */
    invites: Array<SignupInviteResponse>;
    /**
     * Total
     */
    total: number;
};

/**
 * SignupInviteResponse
 */
export type SignupInviteResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Token Hint
     */
    token_hint: string;
    /**
     * Invited Email
     */
    invited_email?: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Max Redemptions
     */
    max_redemptions: number;
    /**
     * Redeemed Count
     */
    redeemed_count: number;
    /**
     * Expires At
     */
    expires_at?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Signup Request Id
     */
    signup_request_id?: string | null;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * SignupInviteStatus
 *
 * Lifecycle states for tenant signup invites.
 */
export type SignupInviteStatus = 'active' | 'revoked' | 'expired' | 'exhausted';

/**
 * SignupRequestApprovalRequest
 */
export type SignupRequestApprovalRequest = {
    /**
     * Note
     *
     * Optional note recorded alongside the invite and decision.
     */
    note?: string | null;
    /**
     * Invite Expires In Hours
     *
     * Optional invite expiry override in hours.
     */
    invite_expires_in_hours?: number | null;
};

/**
 * SignupRequestDecisionResponse
 */
export type SignupRequestDecisionResponse = {
    request: SignupRequestResponse;
    invite?: SignupInviteIssueResponse | null;
};

/**
 * SignupRequestListResponse
 */
export type SignupRequestListResponse = {
    /**
     * Requests
     */
    requests: Array<SignupRequestResponse>;
    /**
     * Total
     */
    total: number;
};

/**
 * SignupRequestPublicRequest
 */
export type SignupRequestPublicRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Organization
     */
    organization: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Message
     *
     * Optional context describing the intended use case.
     */
    message?: string | null;
    /**
     * Accept Terms
     *
     * Indicates that the requester accepted the Terms.
     */
    accept_terms: boolean;
    /**
     * Honeypot
     *
     * Hidden honeypot field used to detect basic bots.
     */
    honeypot?: string | null;
};

/**
 * SignupRequestRejectionRequest
 */
export type SignupRequestRejectionRequest = {
    /**
     * Reason
     *
     * Reason communicated to operators when rejecting a request.
     */
    reason?: string | null;
};

/**
 * SignupRequestResponse
 */
export type SignupRequestResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Organization
     */
    organization: string | null;
    /**
     * Full Name
     */
    full_name: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Decision Reason
     */
    decision_reason?: string | null;
    /**
     * Invite Token Hint
     */
    invite_token_hint?: string | null;
};

/**
 * SignupRequestStatus
 */
export type SignupRequestStatus = 'pending' | 'approved' | 'rejected';

/**
 * StartSubscriptionRequest
 */
export type StartSubscriptionRequest = {
    /**
     * Plan Code
     *
     * Billing plan to activate.
     */
    plan_code: string;
    /**
     * Billing Email
     *
     * Primary billing contact.
     */
    billing_email?: string | null;
    /**
     * Auto Renew
     *
     * Whether the subscription auto-renews.
     */
    auto_renew?: boolean;
    /**
     * Seat Count
     *
     * Optional explicit seat count override.
     */
    seat_count?: number | null;
};

/**
 * StatusIncidentResendRequest
 */
export type StatusIncidentResendRequest = {
    /**
     * Severity
     *
     * Incident severity used to filter subscriptions.
     */
    severity?: 'all' | 'major' | 'maintenance';
    /**
     * Tenant Id
     *
     * Restrict delivery to a specific tenant context.
     */
    tenant_id?: string | null;
};

/**
 * StatusIncidentResendResponse
 */
export type StatusIncidentResendResponse = {
    /**
     * Dispatched
     *
     * Number of subscriptions notified.
     */
    dispatched: number;
};

/**
 * StatusOverviewSchema
 */
export type StatusOverviewSchema = {
    /**
     * State
     *
     * Human-readable health summary.
     */
    state: string;
    /**
     * Description
     *
     * Contextual description displayed on the status page.
     */
    description: string;
    /**
     * Updated At
     *
     * Timestamp of the last health aggregation.
     */
    updated_at: string;
};

/**
 * StatusSubscriptionChallengeRequest
 */
export type StatusSubscriptionChallengeRequest = {
    /**
     * Token
     *
     * Webhook challenge token.
     */
    token: string;
};

/**
 * StatusSubscriptionCreateRequest
 */
export type StatusSubscriptionCreateRequest = {
    /**
     * Channel
     */
    channel: 'email' | 'webhook';
    /**
     * Target
     */
    target: string;
    /**
     * Severity Filter
     *
     * Incident severity filter.
     */
    severity_filter?: 'all' | 'major' | 'maintenance' | null;
    /**
     * Metadata
     *
     * Optional metadata labels.
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * StatusSubscriptionListResponse
 */
export type StatusSubscriptionListResponse = {
    /**
     * Items
     */
    items: Array<StatusSubscriptionResponse>;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
};

/**
 * StatusSubscriptionResponse
 */
export type StatusSubscriptionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Channel
     */
    channel: string;
    /**
     * Severity Filter
     */
    severity_filter: string;
    /**
     * Status
     */
    status: string;
    /**
     * Target Masked
     */
    target_masked: string;
    /**
     * Tenant Id
     */
    tenant_id?: string | null;
    /**
     * Created By
     */
    created_by: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Webhook Secret
     *
     * Signing secret for webhook deliveries (returned on creation only).
     */
    webhook_secret?: string | null;
};

/**
 * StatusSubscriptionVerifyRequest
 */
export type StatusSubscriptionVerifyRequest = {
    /**
     * Token
     *
     * Email verification token.
     */
    token: string;
};

/**
 * StripeEventStatus
 */
export type StripeEventStatus = 'received' | 'processed' | 'failed';

/**
 * SuccessResponse
 *
 * Standard success response envelope.
 */
export type SuccessResponse = {
    /**
     * Success
     *
     * Operation success status flag.
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable summary of the result.
     */
    message: string;
    /**
     * Data
     *
     * Optional payload containing the result.
     */
    data?: unknown | null;
};

/**
 * TenantSettingsResponse
 */
export type TenantSettingsResponse = {
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Billing Contacts
     */
    billing_contacts: Array<BillingContactModel>;
    /**
     * Billing Webhook Url
     */
    billing_webhook_url?: string | null;
    /**
     * Plan Metadata
     */
    plan_metadata: {
        [key: string]: string;
    };
    /**
     * Flags
     */
    flags: {
        [key: string]: boolean;
    };
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * TenantSettingsUpdateRequest
 */
export type TenantSettingsUpdateRequest = {
    /**
     * Billing Contacts
     */
    billing_contacts: Array<BillingContactModel>;
    /**
     * Billing Webhook Url
     */
    billing_webhook_url?: string | null;
    /**
     * Plan Metadata
     */
    plan_metadata: {
        [key: string]: string;
    };
    /**
     * Flags
     */
    flags: {
        [key: string]: boolean;
    };
};

/**
 * TenantSubscriptionResponse
 */
export type TenantSubscriptionResponse = {
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Plan Code
     */
    plan_code: string;
    /**
     * Status
     */
    status: string;
    /**
     * Auto Renew
     */
    auto_renew: boolean;
    /**
     * Billing Email
     */
    billing_email: string | null;
    /**
     * Starts At
     */
    starts_at: string;
    /**
     * Current Period Start
     */
    current_period_start?: string | null;
    /**
     * Current Period End
     */
    current_period_end?: string | null;
    /**
     * Trial Ends At
     */
    trial_ends_at?: string | null;
    /**
     * Cancel At
     */
    cancel_at?: string | null;
    /**
     * Seat Count
     */
    seat_count?: number | null;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * UpdateSubscriptionRequest
 */
export type UpdateSubscriptionRequest = {
    /**
     * Auto Renew
     *
     * Toggle auto-renewal.
     */
    auto_renew?: boolean | null;
    /**
     * Billing Email
     *
     * Override billing contact.
     */
    billing_email?: string | null;
    /**
     * Seat Count
     *
     * Adjust allocated seats.
     */
    seat_count?: number | null;
};

/**
 * UptimeMetricSchema
 */
export type UptimeMetricSchema = {
    /**
     * Label
     */
    label: string;
    /**
     * Value
     */
    value: string;
    /**
     * Helper Text
     */
    helper_text: string;
    /**
     * Trend Value
     */
    trend_value: string;
    /**
     * Trend Tone
     */
    trend_tone: string;
};

/**
 * UsageRecordRequest
 */
export type UsageRecordRequest = {
    /**
     * Feature Key
     *
     * Identifier of the metered feature.
     */
    feature_key: string;
    /**
     * Quantity
     *
     * Units consumed in this report.
     */
    quantity: number;
    /**
     * Idempotency Key
     *
     * Client-provided key to deduplicate usage submissions.
     */
    idempotency_key?: string | null;
    /**
     * Period Start
     *
     * Billing period start (UTC).
     */
    period_start?: string | null;
    /**
     * Period End
     *
     * Billing period end (UTC).
     */
    period_end?: string | null;
};

/**
 * UserLoginRequest
 *
 * Human user login payload.
 */
export type UserLoginRequest = {
    /**
     * Email
     *
     * User email address.
     */
    email: string;
    /**
     * Password
     *
     * Plaintext password to verify.
     */
    password: string;
    /**
     * Tenant Id
     *
     * Tenant UUID when the user belongs to multiple tenants.
     */
    tenant_id?: string | null;
};

/**
 * UserLogoutRequest
 *
 * Payload for revoking a single refresh token.
 */
export type UserLogoutRequest = {
    /**
     * Refresh Token
     *
     * Refresh token to revoke for the current user.
     */
    refresh_token: string;
};

/**
 * UserRefreshRequest
 *
 * Refresh session request payload.
 */
export type UserRefreshRequest = {
    /**
     * Refresh Token
     *
     * Previously issued refresh token.
     */
    refresh_token: string;
};

/**
 * UserRegisterRequest
 *
 * Public signup payload used to create a tenant + owner account.
 */
export type UserRegisterRequest = {
    /**
     * Email
     *
     * Primary user email used for login + billing.
     */
    email: string;
    /**
     * Password
     *
     * Password that meets the platform's minimum complexity requirements.
     */
    password: string;
    /**
     * Tenant Name
     *
     * Display name for the tenant.
     */
    tenant_name: string;
    /**
     * Display Name
     *
     * Optional profile display name for the owner account.
     */
    display_name?: string | null;
    /**
     * Plan Code
     *
     * Requested billing plan (defaults to server configuration when omitted).
     */
    plan_code?: string | null;
    /**
     * Trial Days
     *
     * Optional trial duration hint; ignored unless the deployment explicitly allows overrides.
     */
    trial_days?: number | null;
    /**
     * Accept Terms
     *
     * Indicates whether the caller accepted the Terms of Service.
     */
    accept_terms?: boolean;
    /**
     * Invite Token
     *
     * Invite token or approval code required for invite-only deployments.
     */
    invite_token?: string | null;
};

/**
 * UserRegisterResponse
 *
 * Session response returned by /auth/register with tenant metadata.
 */
export type UserRegisterResponse = {
    /**
     * Access Token
     *
     * Signed JWT access token.
     */
    access_token: string;
    /**
     * Refresh Token
     *
     * Signed JWT refresh token.
     */
    refresh_token: string;
    /**
     * Token Type
     *
     * Token type hint for the Authorization header.
     */
    token_type?: string;
    /**
     * Expires At
     *
     * ISO-8601 timestamp when the access token expires.
     */
    expires_at: string;
    /**
     * Refresh Expires At
     *
     * ISO-8601 timestamp when the refresh token expires.
     */
    refresh_expires_at: string;
    /**
     * Kid
     *
     * Key identifier used to sign the access token.
     */
    kid: string;
    /**
     * Refresh Kid
     *
     * Key identifier used to sign the refresh token.
     */
    refresh_kid: string;
    /**
     * Scopes
     *
     * Authorized scopes attached to the session.
     */
    scopes: Array<string>;
    /**
     * Tenant Id
     *
     * Tenant context associated with the tokens.
     */
    tenant_id: string;
    /**
     * User Id
     *
     * User identifier encoded in the tokens.
     */
    user_id: string;
    /**
     * Email Verified
     *
     * Whether the email has been verified.
     */
    email_verified: boolean;
    /**
     * Session Id
     *
     * Opaque session identifier for device tracking.
     */
    session_id: string;
    /**
     * Tenant Slug
     *
     * URL-safe slug generated for the tenant.
     */
    tenant_slug: string;
};

/**
 * UserSessionItem
 *
 * Single session/device entry for session management UI.
 */
export type UserSessionItem = {
    /**
     * Id
     *
     * Session identifier.
     */
    id: string;
    /**
     * Tenant Id
     *
     * Tenant associated with the session.
     */
    tenant_id: string;
    /**
     * Created At
     *
     * Timestamp when the session was first created.
     */
    created_at: string;
    /**
     * Last Seen At
     *
     * Last activity timestamp for the session.
     */
    last_seen_at: string | null;
    /**
     * Revoked At
     *
     * When the session was revoked (if applicable).
     */
    revoked_at: string | null;
    /**
     * Ip Address Masked
     *
     * Masked IP address for user-facing audits.
     */
    ip_address_masked?: string | null;
    /**
     * Fingerprint
     *
     * Server-generated fingerprint for the IP + user-agent combo.
     */
    fingerprint?: string | null;
    /**
     * Client/browser metadata.
     */
    client: SessionClientInfo;
    /**
     * Approximate location for the session.
     */
    location?: SessionLocationInfo | null;
    /**
     * Current
     *
     * True when this session matches the caller's token context.
     */
    current: boolean;
};

/**
 * UserSessionListResponse
 *
 * Paginated list of user sessions/devices.
 */
export type UserSessionListResponse = {
    /**
     * Sessions
     *
     * Session records for the user.
     */
    sessions: Array<UserSessionItem>;
    /**
     * Total
     *
     * Total number of sessions matching the filter.
     */
    total: number;
    /**
     * Limit
     *
     * Maximum sessions returned in this response.
     */
    limit: number;
    /**
     * Offset
     *
     * Offset applied when querying sessions.
     */
    offset: number;
};

/**
 * UserSessionResponse
 *
 * Bearer credential pair returned after login or refresh.
 */
export type UserSessionResponse = {
    /**
     * Access Token
     *
     * Signed JWT access token.
     */
    access_token: string;
    /**
     * Refresh Token
     *
     * Signed JWT refresh token.
     */
    refresh_token: string;
    /**
     * Token Type
     *
     * Token type hint for the Authorization header.
     */
    token_type?: string;
    /**
     * Expires At
     *
     * ISO-8601 timestamp when the access token expires.
     */
    expires_at: string;
    /**
     * Refresh Expires At
     *
     * ISO-8601 timestamp when the refresh token expires.
     */
    refresh_expires_at: string;
    /**
     * Kid
     *
     * Key identifier used to sign the access token.
     */
    kid: string;
    /**
     * Refresh Kid
     *
     * Key identifier used to sign the refresh token.
     */
    refresh_kid: string;
    /**
     * Scopes
     *
     * Authorized scopes attached to the session.
     */
    scopes: Array<string>;
    /**
     * Tenant Id
     *
     * Tenant context associated with the tokens.
     */
    tenant_id: string;
    /**
     * User Id
     *
     * User identifier encoded in the tokens.
     */
    user_id: string;
    /**
     * Email Verified
     *
     * Whether the email has been verified.
     */
    email_verified: boolean;
    /**
     * Session Id
     *
     * Opaque session identifier for device tracking.
     */
    session_id: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthCheckHealthGetResponse = HealthCheckHealthGetResponses[keyof HealthCheckHealthGetResponses];

export type ReadinessCheckHealthReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type ReadinessCheckHealthReadyGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type ReadinessCheckHealthReadyGetResponse = ReadinessCheckHealthReadyGetResponses[keyof ReadinessCheckHealthReadyGetResponses];

export type HandleStripeWebhookWebhooksStripePostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/webhooks/stripe';
};

export type HandleStripeWebhookWebhooksStripePostResponses = {
    /**
     * Response Handle Stripe Webhook Webhooks Stripe Post
     *
     * Successful Response
     */
    202: {
        [key: string]: boolean;
    };
};

export type HandleStripeWebhookWebhooksStripePostResponse = HandleStripeWebhookWebhooksStripePostResponses[keyof HandleStripeWebhookWebhooksStripePostResponses];

export type LoginForAccessTokenApiV1AuthTokenPostData = {
    body: UserLoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/token';
};

export type LoginForAccessTokenApiV1AuthTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginForAccessTokenApiV1AuthTokenPostError = LoginForAccessTokenApiV1AuthTokenPostErrors[keyof LoginForAccessTokenApiV1AuthTokenPostErrors];

export type LoginForAccessTokenApiV1AuthTokenPostResponses = {
    /**
     * Successful Response
     */
    200: UserSessionResponse;
};

export type LoginForAccessTokenApiV1AuthTokenPostResponse = LoginForAccessTokenApiV1AuthTokenPostResponses[keyof LoginForAccessTokenApiV1AuthTokenPostResponses];

export type RefreshAccessTokenApiV1AuthRefreshPostData = {
    body: UserRefreshRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type RefreshAccessTokenApiV1AuthRefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshAccessTokenApiV1AuthRefreshPostError = RefreshAccessTokenApiV1AuthRefreshPostErrors[keyof RefreshAccessTokenApiV1AuthRefreshPostErrors];

export type RefreshAccessTokenApiV1AuthRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: UserSessionResponse;
};

export type RefreshAccessTokenApiV1AuthRefreshPostResponse = RefreshAccessTokenApiV1AuthRefreshPostResponses[keyof RefreshAccessTokenApiV1AuthRefreshPostResponses];

export type LogoutSessionApiV1AuthLogoutPostData = {
    body: UserLogoutRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutSessionApiV1AuthLogoutPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutSessionApiV1AuthLogoutPostError = LogoutSessionApiV1AuthLogoutPostErrors[keyof LogoutSessionApiV1AuthLogoutPostErrors];

export type LogoutSessionApiV1AuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponse;
};

export type LogoutSessionApiV1AuthLogoutPostResponse = LogoutSessionApiV1AuthLogoutPostResponses[keyof LogoutSessionApiV1AuthLogoutPostResponses];

export type LogoutAllSessionsApiV1AuthLogoutAllPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout/all';
};

export type LogoutAllSessionsApiV1AuthLogoutAllPostResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponse;
};

export type LogoutAllSessionsApiV1AuthLogoutAllPostResponse = LogoutAllSessionsApiV1AuthLogoutAllPostResponses[keyof LogoutAllSessionsApiV1AuthLogoutAllPostResponses];

export type ListUserSessionsApiV1AuthSessionsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Include Revoked
         *
         * When true, include revoked sessions in the response.
         */
        include_revoked?: boolean;
        /**
         * Limit
         *
         * Maximum number of sessions to return.
         */
        limit?: number;
        /**
         * Offset
         *
         * Offset applied when listing sessions.
         */
        offset?: number;
        /**
         * Tenant Id
         *
         * Optional tenant scope for filtering sessions.
         */
        tenant_id?: string | null;
    };
    url: '/api/v1/auth/sessions';
};

export type ListUserSessionsApiV1AuthSessionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListUserSessionsApiV1AuthSessionsGetError = ListUserSessionsApiV1AuthSessionsGetErrors[keyof ListUserSessionsApiV1AuthSessionsGetErrors];

export type ListUserSessionsApiV1AuthSessionsGetResponses = {
    /**
     * Successful Response
     */
    200: UserSessionListResponse;
};

export type ListUserSessionsApiV1AuthSessionsGetResponse = ListUserSessionsApiV1AuthSessionsGetResponses[keyof ListUserSessionsApiV1AuthSessionsGetResponses];

export type RevokeUserSessionApiV1AuthSessionsSessionIdDeleteData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/auth/sessions/{session_id}';
};

export type RevokeUserSessionApiV1AuthSessionsSessionIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeUserSessionApiV1AuthSessionsSessionIdDeleteError = RevokeUserSessionApiV1AuthSessionsSessionIdDeleteErrors[keyof RevokeUserSessionApiV1AuthSessionsSessionIdDeleteErrors];

export type RevokeUserSessionApiV1AuthSessionsSessionIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponse;
};

export type RevokeUserSessionApiV1AuthSessionsSessionIdDeleteResponse = RevokeUserSessionApiV1AuthSessionsSessionIdDeleteResponses[keyof RevokeUserSessionApiV1AuthSessionsSessionIdDeleteResponses];

export type GetCurrentUserInfoApiV1AuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type GetCurrentUserInfoApiV1AuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponse;
};

export type GetCurrentUserInfoApiV1AuthMeGetResponse = GetCurrentUserInfoApiV1AuthMeGetResponses[keyof GetCurrentUserInfoApiV1AuthMeGetResponses];

export type SendEmailVerificationApiV1AuthEmailSendPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/email/send';
};

export type SendEmailVerificationApiV1AuthEmailSendPostResponses = {
    /**
     * Successful Response
     */
    202: SuccessResponse;
};

export type SendEmailVerificationApiV1AuthEmailSendPostResponse = SendEmailVerificationApiV1AuthEmailSendPostResponses[keyof SendEmailVerificationApiV1AuthEmailSendPostResponses];

export type VerifyEmailTokenApiV1AuthEmailVerifyPostData = {
    body: EmailVerificationConfirmRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/email/verify';
};

export type VerifyEmailTokenApiV1AuthEmailVerifyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyEmailTokenApiV1AuthEmailVerifyPostError = VerifyEmailTokenApiV1AuthEmailVerifyPostErrors[keyof VerifyEmailTokenApiV1AuthEmailVerifyPostErrors];

export type VerifyEmailTokenApiV1AuthEmailVerifyPostResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponse;
};

export type VerifyEmailTokenApiV1AuthEmailVerifyPostResponse = VerifyEmailTokenApiV1AuthEmailVerifyPostResponses[keyof VerifyEmailTokenApiV1AuthEmailVerifyPostResponses];

export type RequestPasswordResetApiV1AuthPasswordForgotPostData = {
    body: PasswordForgotRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/password/forgot';
};

export type RequestPasswordResetApiV1AuthPasswordForgotPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RequestPasswordResetApiV1AuthPasswordForgotPostError = RequestPasswordResetApiV1AuthPasswordForgotPostErrors[keyof RequestPasswordResetApiV1AuthPasswordForgotPostErrors];

export type RequestPasswordResetApiV1AuthPasswordForgotPostResponses = {
    /**
     * Successful Response
     */
    202: SuccessResponse;
};

export type RequestPasswordResetApiV1AuthPasswordForgotPostResponse = RequestPasswordResetApiV1AuthPasswordForgotPostResponses[keyof RequestPasswordResetApiV1AuthPasswordForgotPostResponses];

export type ConfirmPasswordResetApiV1AuthPasswordConfirmPostData = {
    body: PasswordResetConfirmRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/password/confirm';
};

export type ConfirmPasswordResetApiV1AuthPasswordConfirmPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConfirmPasswordResetApiV1AuthPasswordConfirmPostError = ConfirmPasswordResetApiV1AuthPasswordConfirmPostErrors[keyof ConfirmPasswordResetApiV1AuthPasswordConfirmPostErrors];

export type ConfirmPasswordResetApiV1AuthPasswordConfirmPostResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponse;
};

export type ConfirmPasswordResetApiV1AuthPasswordConfirmPostResponse = ConfirmPasswordResetApiV1AuthPasswordConfirmPostResponses[keyof ConfirmPasswordResetApiV1AuthPasswordConfirmPostResponses];

export type ChangePasswordApiV1AuthPasswordChangePostData = {
    body: PasswordChangeRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/password/change';
};

export type ChangePasswordApiV1AuthPasswordChangePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangePasswordApiV1AuthPasswordChangePostError = ChangePasswordApiV1AuthPasswordChangePostErrors[keyof ChangePasswordApiV1AuthPasswordChangePostErrors];

export type ChangePasswordApiV1AuthPasswordChangePostResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponse;
};

export type ChangePasswordApiV1AuthPasswordChangePostResponse = ChangePasswordApiV1AuthPasswordChangePostResponses[keyof ChangePasswordApiV1AuthPasswordChangePostResponses];

export type AdminResetPasswordApiV1AuthPasswordResetPostData = {
    body: PasswordResetRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/password/reset';
};

export type AdminResetPasswordApiV1AuthPasswordResetPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminResetPasswordApiV1AuthPasswordResetPostError = AdminResetPasswordApiV1AuthPasswordResetPostErrors[keyof AdminResetPasswordApiV1AuthPasswordResetPostErrors];

export type AdminResetPasswordApiV1AuthPasswordResetPostResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponse;
};

export type AdminResetPasswordApiV1AuthPasswordResetPostResponse = AdminResetPasswordApiV1AuthPasswordResetPostResponses[keyof AdminResetPasswordApiV1AuthPasswordResetPostResponses];

export type IssueServiceAccountTokenApiV1AuthServiceAccountsIssuePostData = {
    body: ServiceAccountIssueRequest;
    headers: {
        /**
         * Authorization
         */
        Authorization: string;
        /**
         * X-Vault-Payload
         */
        'X-Vault-Payload'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/service-accounts/issue';
};

export type IssueServiceAccountTokenApiV1AuthServiceAccountsIssuePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IssueServiceAccountTokenApiV1AuthServiceAccountsIssuePostError = IssueServiceAccountTokenApiV1AuthServiceAccountsIssuePostErrors[keyof IssueServiceAccountTokenApiV1AuthServiceAccountsIssuePostErrors];

export type IssueServiceAccountTokenApiV1AuthServiceAccountsIssuePostResponses = {
    /**
     * Successful Response
     */
    201: ServiceAccountTokenResponse;
};

export type IssueServiceAccountTokenApiV1AuthServiceAccountsIssuePostResponse = IssueServiceAccountTokenApiV1AuthServiceAccountsIssuePostResponses[keyof IssueServiceAccountTokenApiV1AuthServiceAccountsIssuePostResponses];

export type IssueServiceAccountTokenFromBrowserApiV1AuthServiceAccountsBrowserIssuePostData = {
    body: BrowserServiceAccountIssueRequest;
    headers?: {
        /**
         * X-Operator-Override
         */
        'X-Operator-Override'?: string | null;
        /**
         * X-Operator-Reason
         */
        'X-Operator-Reason'?: string | null;
        /**
         * X-Tenant-Id
         */
        'X-Tenant-Id'?: string | null;
        /**
         * X-Tenant-Role
         */
        'X-Tenant-Role'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/service-accounts/browser-issue';
};

export type IssueServiceAccountTokenFromBrowserApiV1AuthServiceAccountsBrowserIssuePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IssueServiceAccountTokenFromBrowserApiV1AuthServiceAccountsBrowserIssuePostError = IssueServiceAccountTokenFromBrowserApiV1AuthServiceAccountsBrowserIssuePostErrors[keyof IssueServiceAccountTokenFromBrowserApiV1AuthServiceAccountsBrowserIssuePostErrors];

export type IssueServiceAccountTokenFromBrowserApiV1AuthServiceAccountsBrowserIssuePostResponses = {
    /**
     * Successful Response
     */
    201: ServiceAccountTokenResponse;
};

export type IssueServiceAccountTokenFromBrowserApiV1AuthServiceAccountsBrowserIssuePostResponse = IssueServiceAccountTokenFromBrowserApiV1AuthServiceAccountsBrowserIssuePostResponses[keyof IssueServiceAccountTokenFromBrowserApiV1AuthServiceAccountsBrowserIssuePostResponses];

export type ListServiceAccountTokensApiV1AuthServiceAccountsTokensGetData = {
    body?: never;
    headers?: {
        /**
         * X-Operator-Override
         */
        'X-Operator-Override'?: string | null;
        /**
         * X-Operator-Reason
         */
        'X-Operator-Reason'?: string | null;
        /**
         * X-Tenant-Id
         */
        'X-Tenant-Id'?: string | null;
        /**
         * X-Tenant-Role
         */
        'X-Tenant-Role'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Account
         *
         * Filter by service-account identifier (substring match).
         */
        account?: string | null;
        /**
         * Fingerprint
         *
         * Filter by stored fingerprint.
         */
        fingerprint?: string | null;
        /**
         * Token status filter (active, revoked, all).
         */
        status?: ServiceAccountTokenStatus;
        /**
         * Tenant Id
         *
         * Tenant UUID to filter (operator override only).
         */
        tenant_id?: string | null;
        /**
         * Include Global
         *
         * Include tenantless tokens (operator override only).
         */
        include_global?: boolean;
        /**
         * Limit
         *
         * Max tokens to return.
         */
        limit?: number;
        /**
         * Offset
         *
         * Offset for pagination.
         */
        offset?: number;
    };
    url: '/api/v1/auth/service-accounts/tokens';
};

export type ListServiceAccountTokensApiV1AuthServiceAccountsTokensGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListServiceAccountTokensApiV1AuthServiceAccountsTokensGetError = ListServiceAccountTokensApiV1AuthServiceAccountsTokensGetErrors[keyof ListServiceAccountTokensApiV1AuthServiceAccountsTokensGetErrors];

export type ListServiceAccountTokensApiV1AuthServiceAccountsTokensGetResponses = {
    /**
     * Successful Response
     */
    200: ServiceAccountTokenListResponse;
};

export type ListServiceAccountTokensApiV1AuthServiceAccountsTokensGetResponse = ListServiceAccountTokensApiV1AuthServiceAccountsTokensGetResponses[keyof ListServiceAccountTokensApiV1AuthServiceAccountsTokensGetResponses];

export type RevokeServiceAccountTokenApiV1AuthServiceAccountsTokensJtiRevokePostData = {
    body: ServiceAccountTokenRevokeRequest;
    headers?: {
        /**
         * X-Operator-Override
         */
        'X-Operator-Override'?: string | null;
        /**
         * X-Operator-Reason
         */
        'X-Operator-Reason'?: string | null;
        /**
         * X-Tenant-Id
         */
        'X-Tenant-Id'?: string | null;
        /**
         * X-Tenant-Role
         */
        'X-Tenant-Role'?: string | null;
    };
    path: {
        /**
         * Jti
         *
         * Refresh token identifier (JWT jti).
         */
        jti: string;
    };
    query?: never;
    url: '/api/v1/auth/service-accounts/tokens/{jti}/revoke';
};

export type RevokeServiceAccountTokenApiV1AuthServiceAccountsTokensJtiRevokePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeServiceAccountTokenApiV1AuthServiceAccountsTokensJtiRevokePostError = RevokeServiceAccountTokenApiV1AuthServiceAccountsTokensJtiRevokePostErrors[keyof RevokeServiceAccountTokenApiV1AuthServiceAccountsTokensJtiRevokePostErrors];

export type RevokeServiceAccountTokenApiV1AuthServiceAccountsTokensJtiRevokePostResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponse;
};

export type RevokeServiceAccountTokenApiV1AuthServiceAccountsTokensJtiRevokePostResponse = RevokeServiceAccountTokenApiV1AuthServiceAccountsTokensJtiRevokePostResponses[keyof RevokeServiceAccountTokenApiV1AuthServiceAccountsTokensJtiRevokePostResponses];

export type GetSignupAccessPolicyApiV1AuthSignupPolicyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/signup-policy';
};

export type GetSignupAccessPolicyApiV1AuthSignupPolicyGetResponses = {
    /**
     * Successful Response
     */
    200: SignupAccessPolicyResponse;
};

export type GetSignupAccessPolicyApiV1AuthSignupPolicyGetResponse = GetSignupAccessPolicyApiV1AuthSignupPolicyGetResponses[keyof GetSignupAccessPolicyApiV1AuthSignupPolicyGetResponses];

export type RegisterTenantApiV1AuthRegisterPostData = {
    body: UserRegisterRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterTenantApiV1AuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterTenantApiV1AuthRegisterPostError = RegisterTenantApiV1AuthRegisterPostErrors[keyof RegisterTenantApiV1AuthRegisterPostErrors];

export type RegisterTenantApiV1AuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: UserRegisterResponse;
};

export type RegisterTenantApiV1AuthRegisterPostResponse = RegisterTenantApiV1AuthRegisterPostResponses[keyof RegisterTenantApiV1AuthRegisterPostResponses];

export type SubmitAccessRequestApiV1AuthRequestAccessPostData = {
    body: SignupRequestPublicRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/request-access';
};

export type SubmitAccessRequestApiV1AuthRequestAccessPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitAccessRequestApiV1AuthRequestAccessPostError = SubmitAccessRequestApiV1AuthRequestAccessPostErrors[keyof SubmitAccessRequestApiV1AuthRequestAccessPostErrors];

export type SubmitAccessRequestApiV1AuthRequestAccessPostResponses = {
    /**
     * Successful Response
     */
    202: SignupAccessPolicyResponse;
};

export type SubmitAccessRequestApiV1AuthRequestAccessPostResponse = SubmitAccessRequestApiV1AuthRequestAccessPostResponses[keyof SubmitAccessRequestApiV1AuthRequestAccessPostResponses];

export type ListSignupRequestsApiV1AuthSignupRequestsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: SignupRequestStatus | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/v1/auth/signup-requests';
};

export type ListSignupRequestsApiV1AuthSignupRequestsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSignupRequestsApiV1AuthSignupRequestsGetError = ListSignupRequestsApiV1AuthSignupRequestsGetErrors[keyof ListSignupRequestsApiV1AuthSignupRequestsGetErrors];

export type ListSignupRequestsApiV1AuthSignupRequestsGetResponses = {
    /**
     * Successful Response
     */
    200: SignupRequestListResponse;
};

export type ListSignupRequestsApiV1AuthSignupRequestsGetResponse = ListSignupRequestsApiV1AuthSignupRequestsGetResponses[keyof ListSignupRequestsApiV1AuthSignupRequestsGetResponses];

export type ApproveSignupRequestApiV1AuthSignupRequestsRequestIdApprovePostData = {
    body: SignupRequestApprovalRequest;
    path: {
        /**
         * Request Id
         */
        request_id: string;
    };
    query?: never;
    url: '/api/v1/auth/signup-requests/{request_id}/approve';
};

export type ApproveSignupRequestApiV1AuthSignupRequestsRequestIdApprovePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApproveSignupRequestApiV1AuthSignupRequestsRequestIdApprovePostError = ApproveSignupRequestApiV1AuthSignupRequestsRequestIdApprovePostErrors[keyof ApproveSignupRequestApiV1AuthSignupRequestsRequestIdApprovePostErrors];

export type ApproveSignupRequestApiV1AuthSignupRequestsRequestIdApprovePostResponses = {
    /**
     * Successful Response
     */
    200: SignupRequestDecisionResponse;
};

export type ApproveSignupRequestApiV1AuthSignupRequestsRequestIdApprovePostResponse = ApproveSignupRequestApiV1AuthSignupRequestsRequestIdApprovePostResponses[keyof ApproveSignupRequestApiV1AuthSignupRequestsRequestIdApprovePostResponses];

export type RejectSignupRequestApiV1AuthSignupRequestsRequestIdRejectPostData = {
    body: SignupRequestRejectionRequest;
    path: {
        /**
         * Request Id
         */
        request_id: string;
    };
    query?: never;
    url: '/api/v1/auth/signup-requests/{request_id}/reject';
};

export type RejectSignupRequestApiV1AuthSignupRequestsRequestIdRejectPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RejectSignupRequestApiV1AuthSignupRequestsRequestIdRejectPostError = RejectSignupRequestApiV1AuthSignupRequestsRequestIdRejectPostErrors[keyof RejectSignupRequestApiV1AuthSignupRequestsRequestIdRejectPostErrors];

export type RejectSignupRequestApiV1AuthSignupRequestsRequestIdRejectPostResponses = {
    /**
     * Successful Response
     */
    200: SignupRequestDecisionResponse;
};

export type RejectSignupRequestApiV1AuthSignupRequestsRequestIdRejectPostResponse = RejectSignupRequestApiV1AuthSignupRequestsRequestIdRejectPostResponses[keyof RejectSignupRequestApiV1AuthSignupRequestsRequestIdRejectPostResponses];

export type ListInvitesApiV1AuthInvitesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: SignupInviteStatus | null;
        /**
         * Email
         */
        email?: string | null;
        /**
         * Request Id
         */
        request_id?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/v1/auth/invites';
};

export type ListInvitesApiV1AuthInvitesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListInvitesApiV1AuthInvitesGetError = ListInvitesApiV1AuthInvitesGetErrors[keyof ListInvitesApiV1AuthInvitesGetErrors];

export type ListInvitesApiV1AuthInvitesGetResponses = {
    /**
     * Successful Response
     */
    200: SignupInviteListResponse;
};

export type ListInvitesApiV1AuthInvitesGetResponse = ListInvitesApiV1AuthInvitesGetResponses[keyof ListInvitesApiV1AuthInvitesGetResponses];

export type IssueInviteApiV1AuthInvitesPostData = {
    body: SignupInviteIssueRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/invites';
};

export type IssueInviteApiV1AuthInvitesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IssueInviteApiV1AuthInvitesPostError = IssueInviteApiV1AuthInvitesPostErrors[keyof IssueInviteApiV1AuthInvitesPostErrors];

export type IssueInviteApiV1AuthInvitesPostResponses = {
    /**
     * Successful Response
     */
    201: SignupInviteIssueResponse;
};

export type IssueInviteApiV1AuthInvitesPostResponse = IssueInviteApiV1AuthInvitesPostResponses[keyof IssueInviteApiV1AuthInvitesPostResponses];

export type RevokeInviteApiV1AuthInvitesInviteIdRevokePostData = {
    body?: never;
    path: {
        /**
         * Invite Id
         */
        invite_id: string;
    };
    query?: never;
    url: '/api/v1/auth/invites/{invite_id}/revoke';
};

export type RevokeInviteApiV1AuthInvitesInviteIdRevokePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeInviteApiV1AuthInvitesInviteIdRevokePostError = RevokeInviteApiV1AuthInvitesInviteIdRevokePostErrors[keyof RevokeInviteApiV1AuthInvitesInviteIdRevokePostErrors];

export type RevokeInviteApiV1AuthInvitesInviteIdRevokePostResponses = {
    /**
     * Successful Response
     */
    200: SignupInviteResponse;
};

export type RevokeInviteApiV1AuthInvitesInviteIdRevokePostResponse = RevokeInviteApiV1AuthInvitesInviteIdRevokePostResponses[keyof RevokeInviteApiV1AuthInvitesInviteIdRevokePostResponses];

export type ChatWithAgentApiV1ChatPostData = {
    body: AgentChatRequest;
    headers?: {
        /**
         * X-Tenant-Id
         */
        'X-Tenant-Id'?: string | null;
        /**
         * X-Tenant-Role
         */
        'X-Tenant-Role'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/chat';
};

export type ChatWithAgentApiV1ChatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatWithAgentApiV1ChatPostError = ChatWithAgentApiV1ChatPostErrors[keyof ChatWithAgentApiV1ChatPostErrors];

export type ChatWithAgentApiV1ChatPostResponses = {
    /**
     * Successful Response
     */
    200: AgentChatResponse;
};

export type ChatWithAgentApiV1ChatPostResponse = ChatWithAgentApiV1ChatPostResponses[keyof ChatWithAgentApiV1ChatPostResponses];

export type StreamChatWithAgentApiV1ChatStreamPostData = {
    body: AgentChatRequest;
    headers?: {
        /**
         * X-Tenant-Id
         */
        'X-Tenant-Id'?: string | null;
        /**
         * X-Tenant-Role
         */
        'X-Tenant-Role'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/chat/stream';
};

export type StreamChatWithAgentApiV1ChatStreamPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamChatWithAgentApiV1ChatStreamPostError = StreamChatWithAgentApiV1ChatStreamPostErrors[keyof StreamChatWithAgentApiV1ChatStreamPostErrors];

export type StreamChatWithAgentApiV1ChatStreamPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListAvailableAgentsApiV1AgentsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/agents';
};

export type ListAvailableAgentsApiV1AgentsGetResponses = {
    /**
     * Response List Available Agents Api V1 Agents Get
     *
     * Successful Response
     */
    200: Array<AgentSummary>;
};

export type ListAvailableAgentsApiV1AgentsGetResponse = ListAvailableAgentsApiV1AgentsGetResponses[keyof ListAvailableAgentsApiV1AgentsGetResponses];

export type GetAgentStatusApiV1AgentsAgentNameStatusGetData = {
    body?: never;
    path: {
        /**
         * Agent Name
         */
        agent_name: string;
    };
    query?: never;
    url: '/api/v1/agents/{agent_name}/status';
};

export type GetAgentStatusApiV1AgentsAgentNameStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAgentStatusApiV1AgentsAgentNameStatusGetError = GetAgentStatusApiV1AgentsAgentNameStatusGetErrors[keyof GetAgentStatusApiV1AgentsAgentNameStatusGetErrors];

export type GetAgentStatusApiV1AgentsAgentNameStatusGetResponses = {
    /**
     * Successful Response
     */
    200: AgentStatus;
};

export type GetAgentStatusApiV1AgentsAgentNameStatusGetResponse = GetAgentStatusApiV1AgentsAgentNameStatusGetResponses[keyof GetAgentStatusApiV1AgentsAgentNameStatusGetResponses];

export type ListConversationsApiV1ConversationsGetData = {
    body?: never;
    headers?: {
        /**
         * X-Tenant-Id
         */
        'X-Tenant-Id'?: string | null;
        /**
         * X-Tenant-Role
         */
        'X-Tenant-Role'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/conversations';
};

export type ListConversationsApiV1ConversationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListConversationsApiV1ConversationsGetError = ListConversationsApiV1ConversationsGetErrors[keyof ListConversationsApiV1ConversationsGetErrors];

export type ListConversationsApiV1ConversationsGetResponses = {
    /**
     * Response List Conversations Api V1 Conversations Get
     *
     * Successful Response
     */
    200: Array<ConversationSummary>;
};

export type ListConversationsApiV1ConversationsGetResponse = ListConversationsApiV1ConversationsGetResponses[keyof ListConversationsApiV1ConversationsGetResponses];

export type DeleteConversationApiV1ConversationsConversationIdDeleteData = {
    body?: never;
    headers?: {
        /**
         * X-Tenant-Id
         */
        'X-Tenant-Id'?: string | null;
        /**
         * X-Tenant-Role
         */
        'X-Tenant-Role'?: string | null;
    };
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/conversations/{conversation_id}';
};

export type DeleteConversationApiV1ConversationsConversationIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteConversationApiV1ConversationsConversationIdDeleteError = DeleteConversationApiV1ConversationsConversationIdDeleteErrors[keyof DeleteConversationApiV1ConversationsConversationIdDeleteErrors];

export type DeleteConversationApiV1ConversationsConversationIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteConversationApiV1ConversationsConversationIdDeleteResponse = DeleteConversationApiV1ConversationsConversationIdDeleteResponses[keyof DeleteConversationApiV1ConversationsConversationIdDeleteResponses];

export type GetConversationApiV1ConversationsConversationIdGetData = {
    body?: never;
    headers?: {
        /**
         * X-Tenant-Id
         */
        'X-Tenant-Id'?: string | null;
        /**
         * X-Tenant-Role
         */
        'X-Tenant-Role'?: string | null;
    };
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/conversations/{conversation_id}';
};

export type GetConversationApiV1ConversationsConversationIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConversationApiV1ConversationsConversationIdGetError = GetConversationApiV1ConversationsConversationIdGetErrors[keyof GetConversationApiV1ConversationsConversationIdGetErrors];

export type GetConversationApiV1ConversationsConversationIdGetResponses = {
    /**
     * Successful Response
     */
    200: ConversationHistory;
};

export type GetConversationApiV1ConversationsConversationIdGetResponse = GetConversationApiV1ConversationsConversationIdGetResponses[keyof GetConversationApiV1ConversationsConversationIdGetResponses];

export type ListAvailableToolsApiV1ToolsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tools';
};

export type ListAvailableToolsApiV1ToolsGetResponses = {
    /**
     * Response List Available Tools Api V1 Tools Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ListAvailableToolsApiV1ToolsGetResponse = ListAvailableToolsApiV1ToolsGetResponses[keyof ListAvailableToolsApiV1ToolsGetResponses];

export type GetPlatformStatusApiV1StatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/status';
};

export type GetPlatformStatusApiV1StatusGetResponses = {
    /**
     * Successful Response
     */
    200: PlatformStatusResponse;
};

export type GetPlatformStatusApiV1StatusGetResponse = GetPlatformStatusApiV1StatusGetResponses[keyof GetPlatformStatusApiV1StatusGetResponses];

export type GetPlatformStatusRssApiV1StatusRssGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/status/rss';
};

export type GetPlatformStatusRssApiV1StatusRssGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListStatusSubscriptionsApiV1StatusSubscriptionsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Tenant Id
         *
         * Tenant identifier to inspect (operators only).
         */
        tenant_id?: string | null;
    };
    url: '/api/v1/status/subscriptions';
};

export type ListStatusSubscriptionsApiV1StatusSubscriptionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListStatusSubscriptionsApiV1StatusSubscriptionsGetError = ListStatusSubscriptionsApiV1StatusSubscriptionsGetErrors[keyof ListStatusSubscriptionsApiV1StatusSubscriptionsGetErrors];

export type ListStatusSubscriptionsApiV1StatusSubscriptionsGetResponses = {
    /**
     * Successful Response
     */
    200: StatusSubscriptionListResponse;
};

export type ListStatusSubscriptionsApiV1StatusSubscriptionsGetResponse = ListStatusSubscriptionsApiV1StatusSubscriptionsGetResponses[keyof ListStatusSubscriptionsApiV1StatusSubscriptionsGetResponses];

export type CreateStatusSubscriptionApiV1StatusSubscriptionsPostData = {
    body: StatusSubscriptionCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/status/subscriptions';
};

export type CreateStatusSubscriptionApiV1StatusSubscriptionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateStatusSubscriptionApiV1StatusSubscriptionsPostError = CreateStatusSubscriptionApiV1StatusSubscriptionsPostErrors[keyof CreateStatusSubscriptionApiV1StatusSubscriptionsPostErrors];

export type CreateStatusSubscriptionApiV1StatusSubscriptionsPostResponses = {
    /**
     * Successful Response
     */
    201: StatusSubscriptionResponse;
};

export type CreateStatusSubscriptionApiV1StatusSubscriptionsPostResponse = CreateStatusSubscriptionApiV1StatusSubscriptionsPostResponses[keyof CreateStatusSubscriptionApiV1StatusSubscriptionsPostResponses];

export type VerifyStatusSubscriptionApiV1StatusSubscriptionsVerifyPostData = {
    body: StatusSubscriptionVerifyRequest;
    path?: never;
    query?: never;
    url: '/api/v1/status/subscriptions/verify';
};

export type VerifyStatusSubscriptionApiV1StatusSubscriptionsVerifyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyStatusSubscriptionApiV1StatusSubscriptionsVerifyPostError = VerifyStatusSubscriptionApiV1StatusSubscriptionsVerifyPostErrors[keyof VerifyStatusSubscriptionApiV1StatusSubscriptionsVerifyPostErrors];

export type VerifyStatusSubscriptionApiV1StatusSubscriptionsVerifyPostResponses = {
    /**
     * Successful Response
     */
    200: StatusSubscriptionResponse;
};

export type VerifyStatusSubscriptionApiV1StatusSubscriptionsVerifyPostResponse = VerifyStatusSubscriptionApiV1StatusSubscriptionsVerifyPostResponses[keyof VerifyStatusSubscriptionApiV1StatusSubscriptionsVerifyPostResponses];

export type ConfirmWebhookChallengeApiV1StatusSubscriptionsChallengePostData = {
    body: StatusSubscriptionChallengeRequest;
    path?: never;
    query?: never;
    url: '/api/v1/status/subscriptions/challenge';
};

export type ConfirmWebhookChallengeApiV1StatusSubscriptionsChallengePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConfirmWebhookChallengeApiV1StatusSubscriptionsChallengePostError = ConfirmWebhookChallengeApiV1StatusSubscriptionsChallengePostErrors[keyof ConfirmWebhookChallengeApiV1StatusSubscriptionsChallengePostErrors];

export type ConfirmWebhookChallengeApiV1StatusSubscriptionsChallengePostResponses = {
    /**
     * Successful Response
     */
    200: StatusSubscriptionResponse;
};

export type ConfirmWebhookChallengeApiV1StatusSubscriptionsChallengePostResponse = ConfirmWebhookChallengeApiV1StatusSubscriptionsChallengePostResponses[keyof ConfirmWebhookChallengeApiV1StatusSubscriptionsChallengePostResponses];

export type RevokeStatusSubscriptionApiV1StatusSubscriptionsSubscriptionIdDeleteData = {
    body?: never;
    path: {
        /**
         * Subscription Id
         */
        subscription_id: string;
    };
    query?: {
        /**
         * Token
         *
         * Unsubscribe token for email subscribers.
         */
        token?: string | null;
    };
    url: '/api/v1/status/subscriptions/{subscription_id}';
};

export type RevokeStatusSubscriptionApiV1StatusSubscriptionsSubscriptionIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeStatusSubscriptionApiV1StatusSubscriptionsSubscriptionIdDeleteError = RevokeStatusSubscriptionApiV1StatusSubscriptionsSubscriptionIdDeleteErrors[keyof RevokeStatusSubscriptionApiV1StatusSubscriptionsSubscriptionIdDeleteErrors];

export type RevokeStatusSubscriptionApiV1StatusSubscriptionsSubscriptionIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RevokeStatusSubscriptionApiV1StatusSubscriptionsSubscriptionIdDeleteResponse = RevokeStatusSubscriptionApiV1StatusSubscriptionsSubscriptionIdDeleteResponses[keyof RevokeStatusSubscriptionApiV1StatusSubscriptionsSubscriptionIdDeleteResponses];

export type ResendStatusIncidentApiV1StatusIncidentsIncidentIdResendPostData = {
    body: StatusIncidentResendRequest;
    path: {
        /**
         * Incident Id
         */
        incident_id: string;
    };
    query?: never;
    url: '/api/v1/status/incidents/{incident_id}/resend';
};

export type ResendStatusIncidentApiV1StatusIncidentsIncidentIdResendPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResendStatusIncidentApiV1StatusIncidentsIncidentIdResendPostError = ResendStatusIncidentApiV1StatusIncidentsIncidentIdResendPostErrors[keyof ResendStatusIncidentApiV1StatusIncidentsIncidentIdResendPostErrors];

export type ResendStatusIncidentApiV1StatusIncidentsIncidentIdResendPostResponses = {
    /**
     * Successful Response
     */
    202: StatusIncidentResendResponse;
};

export type ResendStatusIncidentApiV1StatusIncidentsIncidentIdResendPostResponse = ResendStatusIncidentApiV1StatusIncidentsIncidentIdResendPostResponses[keyof ResendStatusIncidentApiV1StatusIncidentsIncidentIdResendPostResponses];

export type GetPlatformStatusRssAliasApiV1StatusRssGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/status.rss';
};

export type GetPlatformStatusRssAliasApiV1StatusRssGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTenantSettingsApiV1TenantsSettingsGetData = {
    body?: never;
    headers?: {
        /**
         * X-Tenant-Id
         */
        'X-Tenant-Id'?: string | null;
        /**
         * X-Tenant-Role
         */
        'X-Tenant-Role'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/tenants/settings';
};

export type GetTenantSettingsApiV1TenantsSettingsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTenantSettingsApiV1TenantsSettingsGetError = GetTenantSettingsApiV1TenantsSettingsGetErrors[keyof GetTenantSettingsApiV1TenantsSettingsGetErrors];

export type GetTenantSettingsApiV1TenantsSettingsGetResponses = {
    /**
     * Successful Response
     */
    200: TenantSettingsResponse;
};

export type GetTenantSettingsApiV1TenantsSettingsGetResponse = GetTenantSettingsApiV1TenantsSettingsGetResponses[keyof GetTenantSettingsApiV1TenantsSettingsGetResponses];

export type UpdateTenantSettingsApiV1TenantsSettingsPutData = {
    body: TenantSettingsUpdateRequest;
    headers?: {
        /**
         * X-Tenant-Id
         */
        'X-Tenant-Id'?: string | null;
        /**
         * X-Tenant-Role
         */
        'X-Tenant-Role'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/tenants/settings';
};

export type UpdateTenantSettingsApiV1TenantsSettingsPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTenantSettingsApiV1TenantsSettingsPutError = UpdateTenantSettingsApiV1TenantsSettingsPutErrors[keyof UpdateTenantSettingsApiV1TenantsSettingsPutErrors];

export type UpdateTenantSettingsApiV1TenantsSettingsPutResponses = {
    /**
     * Successful Response
     */
    200: TenantSettingsResponse;
};

export type UpdateTenantSettingsApiV1TenantsSettingsPutResponse = UpdateTenantSettingsApiV1TenantsSettingsPutResponses[keyof UpdateTenantSettingsApiV1TenantsSettingsPutResponses];

export type ListBillingPlansApiV1BillingPlansGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/billing/plans';
};

export type ListBillingPlansApiV1BillingPlansGetResponses = {
    /**
     * Response List Billing Plans Api V1 Billing Plans Get
     *
     * Successful Response
     */
    200: Array<BillingPlanResponse>;
};

export type ListBillingPlansApiV1BillingPlansGetResponse = ListBillingPlansApiV1BillingPlansGetResponses[keyof ListBillingPlansApiV1BillingPlansGetResponses];

export type GetTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGetData = {
    body?: never;
    headers?: {
        /**
         * X-Tenant-Id
         */
        'X-Tenant-Id'?: string | null;
        /**
         * X-Tenant-Role
         */
        'X-Tenant-Role'?: string | null;
    };
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: never;
    url: '/api/v1/billing/tenants/{tenant_id}/subscription';
};

export type GetTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGetError = GetTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGetErrors[keyof GetTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGetErrors];

export type GetTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGetResponses = {
    /**
     * Successful Response
     */
    200: TenantSubscriptionResponse;
};

export type GetTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGetResponse = GetTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGetResponses[keyof GetTenantSubscriptionApiV1BillingTenantsTenantIdSubscriptionGetResponses];

export type UpdateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatchData = {
    body: UpdateSubscriptionRequest;
    headers?: {
        /**
         * X-Tenant-Id
         */
        'X-Tenant-Id'?: string | null;
        /**
         * X-Tenant-Role
         */
        'X-Tenant-Role'?: string | null;
    };
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: never;
    url: '/api/v1/billing/tenants/{tenant_id}/subscription';
};

export type UpdateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatchError = UpdateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatchErrors[keyof UpdateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatchErrors];

export type UpdateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatchResponses = {
    /**
     * Successful Response
     */
    200: TenantSubscriptionResponse;
};

export type UpdateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatchResponse = UpdateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatchResponses[keyof UpdateSubscriptionApiV1BillingTenantsTenantIdSubscriptionPatchResponses];

export type StartSubscriptionApiV1BillingTenantsTenantIdSubscriptionPostData = {
    body: StartSubscriptionRequest;
    headers?: {
        /**
         * X-Tenant-Id
         */
        'X-Tenant-Id'?: string | null;
        /**
         * X-Tenant-Role
         */
        'X-Tenant-Role'?: string | null;
    };
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: never;
    url: '/api/v1/billing/tenants/{tenant_id}/subscription';
};

export type StartSubscriptionApiV1BillingTenantsTenantIdSubscriptionPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartSubscriptionApiV1BillingTenantsTenantIdSubscriptionPostError = StartSubscriptionApiV1BillingTenantsTenantIdSubscriptionPostErrors[keyof StartSubscriptionApiV1BillingTenantsTenantIdSubscriptionPostErrors];

export type StartSubscriptionApiV1BillingTenantsTenantIdSubscriptionPostResponses = {
    /**
     * Successful Response
     */
    201: TenantSubscriptionResponse;
};

export type StartSubscriptionApiV1BillingTenantsTenantIdSubscriptionPostResponse = StartSubscriptionApiV1BillingTenantsTenantIdSubscriptionPostResponses[keyof StartSubscriptionApiV1BillingTenantsTenantIdSubscriptionPostResponses];

export type CancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPostData = {
    body: CancelSubscriptionRequest;
    headers?: {
        /**
         * X-Tenant-Id
         */
        'X-Tenant-Id'?: string | null;
        /**
         * X-Tenant-Role
         */
        'X-Tenant-Role'?: string | null;
    };
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: never;
    url: '/api/v1/billing/tenants/{tenant_id}/subscription/cancel';
};

export type CancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPostError = CancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPostErrors[keyof CancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPostErrors];

export type CancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPostResponses = {
    /**
     * Successful Response
     */
    200: TenantSubscriptionResponse;
};

export type CancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPostResponse = CancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPostResponses[keyof CancelSubscriptionApiV1BillingTenantsTenantIdSubscriptionCancelPostResponses];

export type RecordUsageApiV1BillingTenantsTenantIdUsagePostData = {
    body: UsageRecordRequest;
    headers?: {
        /**
         * X-Tenant-Id
         */
        'X-Tenant-Id'?: string | null;
        /**
         * X-Tenant-Role
         */
        'X-Tenant-Role'?: string | null;
    };
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: never;
    url: '/api/v1/billing/tenants/{tenant_id}/usage';
};

export type RecordUsageApiV1BillingTenantsTenantIdUsagePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecordUsageApiV1BillingTenantsTenantIdUsagePostError = RecordUsageApiV1BillingTenantsTenantIdUsagePostErrors[keyof RecordUsageApiV1BillingTenantsTenantIdUsagePostErrors];

export type RecordUsageApiV1BillingTenantsTenantIdUsagePostResponses = {
    /**
     * Successful Response
     */
    202: SuccessResponse;
};

export type RecordUsageApiV1BillingTenantsTenantIdUsagePostResponse = RecordUsageApiV1BillingTenantsTenantIdUsagePostResponses[keyof RecordUsageApiV1BillingTenantsTenantIdUsagePostResponses];

export type ListBillingEventsApiV1BillingTenantsTenantIdEventsGetData = {
    body?: never;
    headers?: {
        /**
         * X-Tenant-Id
         */
        'X-Tenant-Id'?: string | null;
        /**
         * X-Tenant-Role
         */
        'X-Tenant-Role'?: string | null;
    };
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: {
        /**
         * Limit
         *
         * Number of events to return.
         */
        limit?: number;
        /**
         * Cursor
         *
         * Opaque cursor returned from the previous page.
         */
        cursor?: string | null;
        /**
         * Event Type
         *
         * Filter by Stripe event type.
         */
        event_type?: string | null;
        /**
         * Processing Status
         *
         * Filter by processing outcome (received/processed/failed).
         */
        processing_status?: StripeEventStatus | null;
    };
    url: '/api/v1/billing/tenants/{tenant_id}/events';
};

export type ListBillingEventsApiV1BillingTenantsTenantIdEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListBillingEventsApiV1BillingTenantsTenantIdEventsGetError = ListBillingEventsApiV1BillingTenantsTenantIdEventsGetErrors[keyof ListBillingEventsApiV1BillingTenantsTenantIdEventsGetErrors];

export type ListBillingEventsApiV1BillingTenantsTenantIdEventsGetResponses = {
    /**
     * Successful Response
     */
    200: BillingEventHistoryResponse;
};

export type ListBillingEventsApiV1BillingTenantsTenantIdEventsGetResponse = ListBillingEventsApiV1BillingTenantsTenantIdEventsGetResponses[keyof ListBillingEventsApiV1BillingTenantsTenantIdEventsGetResponses];

export type BillingEventStreamApiV1BillingStreamGetData = {
    body?: never;
    headers?: {
        /**
         * X-Tenant-Id
         */
        'X-Tenant-Id'?: string | null;
        /**
         * X-Tenant-Role
         */
        'X-Tenant-Role'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/billing/stream';
};

export type BillingEventStreamApiV1BillingStreamGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BillingEventStreamApiV1BillingStreamGetError = BillingEventStreamApiV1BillingStreamGetErrors[keyof BillingEventStreamApiV1BillingStreamGetErrors];

export type BillingEventStreamApiV1BillingStreamGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
