"""Shared infra contracts and Terraform export specifications."""

from .terraform_spec import (
    AWS_VALIDATIONS,
    AWS_VARIABLES,
    AZURE_VALIDATIONS,
    AZURE_VARIABLES,
    GCP_VALIDATIONS,
    GCP_VARIABLES,
    TerraformAllowedValuesCheck,
    TerraformComparisonCheck,
    TerraformCondition,
    TerraformDisallowedValuesCheck,
    TerraformMapKeyExclusionCheck,
    TerraformProvider,
    TerraformProviderSpec,
    TerraformRangeCheck,
    TerraformRequirementRule,
    TerraformStringPresence,
    TerraformValidationRule,
    TerraformVarCategory,
    TerraformVariableSpec,
    get_provider_spec,
    list_provider_specs,
    matches_condition,
    resolve_required_variables,
    validate_provider_values,
)

__all__ = [
    "AWS_VALIDATIONS",
    "AWS_VARIABLES",
    "AZURE_VALIDATIONS",
    "AZURE_VARIABLES",
    "GCP_VALIDATIONS",
    "GCP_VARIABLES",
    "TerraformAllowedValuesCheck",
    "TerraformComparisonCheck",
    "TerraformCondition",
    "TerraformDisallowedValuesCheck",
    "TerraformMapKeyExclusionCheck",
    "TerraformProvider",
    "TerraformProviderSpec",
    "TerraformRangeCheck",
    "TerraformRequirementRule",
    "TerraformStringPresence",
    "TerraformValidationRule",
    "TerraformVarCategory",
    "TerraformVariableSpec",
    "get_provider_spec",
    "list_provider_specs",
    "matches_condition",
    "resolve_required_variables",
    "validate_provider_values",
]
